// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lucidchain/proto/checkpoint/v1/checkpoint.proto

package types

import (
	bytes "bytes"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Checkpoint is a finalized commitment submitted by a registered sidechain.
// It stores only cryptographic commitments -- never raw application data.
type Checkpoint struct {
	// ID of the sidechain this checkpoint belongs to (see x/sidechain.Sidechain.id).
	SidechainId string `protobuf:"bytes,1,opt,name=sidechain_id,json=sidechainId,proto3" json:"sidechain_id,omitempty"`
	// Monotonically increasing sequence number for this sidechain's checkpoints.
	// Must equal the previous checkpoint's sequence + 1 (no gaps, no reordering).
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Merkle root (or equivalent state commitment) of the batch of records
	// this checkpoint covers, as computed off-chain by the sidechain.
	StateRoot []byte `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// Hash of the immediately preceding checkpoint for this sidechain,
	// forming a verifiable chain. Empty for sequence == 1.
	PreviousCheckpointHash []byte `protobuf:"bytes,4,opt,name=previous_checkpoint_hash,json=previousCheckpointHash,proto3" json:"previous_checkpoint_hash,omitempty"`
	// Number of individual records/events committed in this batch.
	// Informational; used for fee calculation and monitoring, not consensus-critical.
	RecordCount uint64 `protobuf:"varint,5,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	// Signatures from the sidechain's authorized checkpoint signer key(s).
	// Must meet the sidechain's configured signature_threshold.
	Signatures []*Signature `protobuf:"bytes,6,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Block height and time at which this checkpoint was finalized on this chain.
	FinalizedHeight uint64    `protobuf:"varint,7,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	FinalizedAt     time.Time `protobuf:"bytes,8,opt,name=finalized_at,json=finalizedAt,proto3,stdtime" json:"finalized_at"`
	// Optional off-chain pointer (e.g. IPFS CID, URI) to where the full batch
	// data or an index is retrievable. Not verified on-chain.
	DataPointer string `protobuf:"bytes,9,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca59191fd323e4f, []int{0}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetSidechainId() string {
	if m != nil {
		return m.SidechainId
	}
	return ""
}

func (m *Checkpoint) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Checkpoint) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *Checkpoint) GetPreviousCheckpointHash() []byte {
	if m != nil {
		return m.PreviousCheckpointHash
	}
	return nil
}

func (m *Checkpoint) GetRecordCount() uint64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *Checkpoint) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Checkpoint) GetFinalizedHeight() uint64 {
	if m != nil {
		return m.FinalizedHeight
	}
	return 0
}

func (m *Checkpoint) GetFinalizedAt() time.Time {
	if m != nil {
		return m.FinalizedAt
	}
	return time.Time{}
}

func (m *Checkpoint) GetDataPointer() string {
	if m != nil {
		return m.DataPointer
	}
	return ""
}

type Signature struct {
	Pubkey    string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca59191fd323e4f, []int{1}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return m.Size()
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Params defines module-wide parameters, settable via governance.
type Params struct {
	// Base fee per checkpoint submission, in the native token's smallest denom.
	BaseFee cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=base_fee,json=baseFee,proto3,customtype=cosmossdk.io/math.Int" json:"base_fee"`
	// Additional fee per record in the batch (record_count), to price large batches fairly.
	PerRecordFee cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=per_record_fee,json=perRecordFee,proto3,customtype=cosmossdk.io/math.Int" json:"per_record_fee"`
	// Maximum record_count allowed to be declared in a single checkpoint.
	MaxRecordsPerCheckpoint uint64 `protobuf:"varint,3,opt,name=max_records_per_checkpoint,json=maxRecordsPerCheckpoint,proto3" json:"max_records_per_checkpoint,omitempty"`
	// Maximum size in bytes of the data_pointer field.
	MaxDataPointerBytes uint32 `protobuf:"varint,4,opt,name=max_data_pointer_bytes,json=maxDataPointerBytes,proto3" json:"max_data_pointer_bytes,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca59191fd323e4f, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxRecordsPerCheckpoint() uint64 {
	if m != nil {
		return m.MaxRecordsPerCheckpoint
	}
	return 0
}

func (m *Params) GetMaxDataPointerBytes() uint32 {
	if m != nil {
		return m.MaxDataPointerBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*Checkpoint)(nil), "lucidchain.proto.checkpoint.v1.Checkpoint")
	proto.RegisterType((*Signature)(nil), "lucidchain.proto.checkpoint.v1.Signature")
	proto.RegisterType((*Params)(nil), "lucidchain.proto.checkpoint.v1.Params")
}

func init() {
	proto.RegisterFile("lucidchain/proto/checkpoint/v1/checkpoint.proto", fileDescriptor_7ca59191fd323e4f)
}

var fileDescriptor_7ca59191fd323e4f = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x8d, 0xdb, 0xbc, 0x34, 0x99, 0xe4, 0x01, 0x1a, 0xa0, 0x58, 0x11, 0x75, 0x42, 0x57, 0xe9,
	0xc6, 0x56, 0xda, 0x4d, 0x05, 0xab, 0x26, 0x08, 0x1a, 0xb1, 0x89, 0x0c, 0x2b, 0x36, 0xd6, 0xd8,
	0xbe, 0xb1, 0x47, 0x89, 0x3d, 0xc6, 0x33, 0x8e, 0x12, 0xbe, 0xa2, 0x9f, 0xc0, 0x1f, 0xf0, 0x1b,
	0x5d, 0x76, 0x89, 0x58, 0x14, 0x94, 0x6c, 0xf8, 0x0b, 0x90, 0x67, 0x12, 0xdb, 0x2b, 0xd8, 0x79,
	0xce, 0xdc, 0x73, 0xee, 0xf1, 0xb9, 0x73, 0x91, 0xb5, 0xc8, 0x3c, 0xea, 0x7b, 0x21, 0xa1, 0xb1,
	0x95, 0xa4, 0x4c, 0x30, 0xcb, 0x0b, 0xc1, 0x9b, 0x27, 0x8c, 0xc6, 0xc2, 0x5a, 0x0e, 0x2b, 0x27,
	0x53, 0x5e, 0x63, 0xa3, 0x24, 0x28, 0xc4, 0xac, 0x94, 0x2c, 0x87, 0xdd, 0x27, 0x01, 0x0b, 0x98,
	0x52, 0xca, 0xbf, 0x54, 0x4d, 0xb7, 0x17, 0x30, 0x16, 0x2c, 0x40, 0xb5, 0x70, 0xb3, 0x99, 0x25,
	0x68, 0x04, 0x5c, 0x90, 0x28, 0x51, 0x05, 0xa7, 0x5f, 0x0f, 0x11, 0x1a, 0x17, 0x42, 0xf8, 0x05,
	0xea, 0x70, 0xea, 0x83, 0x6c, 0xe3, 0x50, 0x5f, 0xd7, 0xfa, 0xda, 0xa0, 0x65, 0xb7, 0x0b, 0x6c,
	0xe2, 0xe3, 0x2e, 0x6a, 0x72, 0xf8, 0x94, 0x41, 0xec, 0x81, 0x7e, 0xd0, 0xd7, 0x06, 0x75, 0xbb,
	0x38, 0xe3, 0x13, 0x84, 0xb8, 0x20, 0x02, 0x9c, 0x94, 0x31, 0xa1, 0x1f, 0xf6, 0xb5, 0x41, 0xc7,
	0x6e, 0x49, 0xc4, 0x66, 0x4c, 0xe0, 0x4b, 0xa4, 0x27, 0x29, 0x2c, 0x29, 0xcb, 0xb8, 0x53, 0xba,
	0x77, 0x42, 0xc2, 0x43, 0xbd, 0x2e, 0x8b, 0x8f, 0xf7, 0xf7, 0xa5, 0xa7, 0x6b, 0xc2, 0xc3, 0xdc,
	0x57, 0x0a, 0x1e, 0x4b, 0x7d, 0xc7, 0x63, 0x59, 0x2c, 0xf4, 0xff, 0x64, 0xe3, 0xb6, 0xc2, 0xc6,
	0x39, 0x84, 0x27, 0x08, 0x71, 0x1a, 0xc4, 0x44, 0x64, 0x29, 0x70, 0xbd, 0xd1, 0x3f, 0x1c, 0xb4,
	0xcf, 0xcf, 0xcc, 0xbf, 0xa7, 0x66, 0xbe, 0xdf, 0x33, 0xec, 0x0a, 0x19, 0x9f, 0xa1, 0x47, 0x33,
	0x1a, 0x93, 0x05, 0xfd, 0x0c, 0xbe, 0x13, 0x02, 0x0d, 0x42, 0xa1, 0x1f, 0xc9, 0x8e, 0x0f, 0x0b,
	0xfc, 0x5a, 0xc2, 0xf8, 0x2d, 0xea, 0x94, 0xa5, 0x44, 0xe8, 0xcd, 0xbe, 0x36, 0x68, 0x9f, 0x77,
	0x4d, 0x95, 0xbb, 0xb9, 0xcf, 0xdd, 0xfc, 0xb0, 0xcf, 0x7d, 0xd4, 0xbc, 0xbd, 0xef, 0xd5, 0x6e,
	0x7e, 0xf4, 0x34, 0xbb, 0x5d, 0x30, 0xaf, 0x64, 0xf2, 0x3e, 0x11, 0xc4, 0x91, 0xd6, 0x20, 0xd5,
	0x5b, 0x2a, 0xf9, 0x1c, 0x9b, 0x2a, 0xe8, 0x65, 0xfd, 0xd7, 0x97, 0x9e, 0x76, 0x7a, 0x85, 0x5a,
	0x85, 0x6b, 0x7c, 0x8c, 0x1a, 0x49, 0xe6, 0xce, 0x61, 0xbd, 0x9b, 0xd4, 0xee, 0x84, 0x9f, 0xa3,
	0x56, 0xf1, 0x3f, 0xfa, 0xc1, 0x6e, 0x0e, 0x7b, 0xe0, 0xf4, 0xb7, 0x86, 0x1a, 0x53, 0x92, 0x92,
	0x88, 0xe3, 0x4b, 0xd4, 0x74, 0x09, 0x07, 0x67, 0x06, 0xa0, 0x24, 0x46, 0x27, 0xb9, 0xbf, 0xef,
	0xf7, 0xbd, 0xa7, 0x1e, 0xe3, 0x11, 0xe3, 0xdc, 0x9f, 0x9b, 0x94, 0x59, 0x11, 0x11, 0xa1, 0x39,
	0x89, 0x85, 0x7d, 0x94, 0x97, 0xbf, 0x01, 0xc0, 0x63, 0xf4, 0x20, 0x81, 0xd4, 0xd9, 0x8d, 0x65,
	0x06, 0xaa, 0xcf, 0x3f, 0xf9, 0x9d, 0x04, 0x52, 0x5b, 0x72, 0x72, 0x91, 0x57, 0xa8, 0x1b, 0x91,
	0xd5, 0x4e, 0x84, 0x3b, 0xb9, 0x60, 0x39, 0x20, 0xf9, 0x80, 0xea, 0xf6, 0xb3, 0x88, 0xac, 0x14,
	0x83, 0x4f, 0x21, 0xad, 0x3c, 0xd6, 0x0b, 0x74, 0x9c, 0x93, 0xab, 0xb1, 0x39, 0xee, 0x5a, 0x00,
	0x97, 0x8f, 0xe9, 0x7f, 0xfb, 0x71, 0x44, 0x56, 0xaf, 0xcb, 0xfc, 0x46, 0xf9, 0x95, 0x0a, 0x71,
	0xf4, 0xee, 0x76, 0x63, 0x68, 0x77, 0x1b, 0x43, 0xfb, 0xb9, 0x31, 0xb4, 0x9b, 0xad, 0x51, 0xbb,
	0xdb, 0x1a, 0xb5, 0x6f, 0x5b, 0xa3, 0xf6, 0x71, 0x18, 0x50, 0x11, 0x66, 0xae, 0xe9, 0xb1, 0x48,
	0xed, 0x68, 0x42, 0xd6, 0xd5, 0x65, 0x5d, 0x55, 0x17, 0x55, 0xac, 0x13, 0xe0, 0x6e, 0x43, 0x4e,
	0xf9, 0xe2, 0xcf, 0x00, 0x6e, 0x58, 0xac, 0xd4, 0xd4, 0x03, 0x00, 0x00,
}

func (this *Checkpoint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Checkpoint)
	if !ok {
		that2, ok := that.(Checkpoint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SidechainId != that1.SidechainId {
		return false
	}
	if this.Sequence != that1.Sequence {
		return false
	}
	if !bytes.Equal(this.StateRoot, that1.StateRoot) {
		return false
	}
	if !bytes.Equal(this.PreviousCheckpointHash, that1.PreviousCheckpointHash) {
		return false
	}
	if this.RecordCount != that1.RecordCount {
		return false
	}
	if len(this.Signatures) != len(that1.Signatures) {
		return false
	}
	for i := range this.Signatures {
		if !this.Signatures[i].Equal(that1.Signatures[i]) {
			return false
		}
	}
	if this.FinalizedHeight != that1.FinalizedHeight {
		return false
	}
	if !this.FinalizedAt.Equal(that1.FinalizedAt) {
		return false
	}
	if this.DataPointer != that1.DataPointer {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.BaseFee.Equal(that1.BaseFee) {
		return false
	}
	if !this.PerRecordFee.Equal(that1.PerRecordFee) {
		return false
	}
	if this.MaxRecordsPerCheckpoint != that1.MaxRecordsPerCheckpoint {
		return false
	}
	if this.MaxDataPointerBytes != that1.MaxDataPointerBytes {
		return false
	}
	return true
}
func (m *Checkpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataPointer) > 0 {
		i -= len(m.DataPointer)
		copy(dAtA[i:], m.DataPointer)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.DataPointer)))
		i--
		dAtA[i] = 0x4a
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.FinalizedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.FinalizedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCheckpoint(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x42
	if m.FinalizedHeight != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.FinalizedHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCheckpoint(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.RecordCount != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.RecordCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PreviousCheckpointHash) > 0 {
		i -= len(m.PreviousCheckpointHash)
		copy(dAtA[i:], m.PreviousCheckpointHash)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.PreviousCheckpointHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Sequence != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SidechainId) > 0 {
		i -= len(m.SidechainId)
		copy(dAtA[i:], m.SidechainId)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.SidechainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Signature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Signature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Signature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxDataPointerBytes != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.MaxDataPointerBytes))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxRecordsPerCheckpoint != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.MaxRecordsPerCheckpoint))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.PerRecordFee.Size()
		i -= size
		if _, err := m.PerRecordFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCheckpoint(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.BaseFee.Size()
		i -= size
		if _, err := m.BaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCheckpoint(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintCheckpoint(dAtA []byte, offset int, v uint64) int {
	offset -= sovCheckpoint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Checkpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SidechainId)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovCheckpoint(uint64(m.Sequence))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.PreviousCheckpointHash)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.RecordCount != 0 {
		n += 1 + sovCheckpoint(uint64(m.RecordCount))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovCheckpoint(uint64(l))
		}
	}
	if m.FinalizedHeight != 0 {
		n += 1 + sovCheckpoint(uint64(m.FinalizedHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.FinalizedAt)
	n += 1 + l + sovCheckpoint(uint64(l))
	l = len(m.DataPointer)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *Signature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BaseFee.Size()
	n += 1 + l + sovCheckpoint(uint64(l))
	l = m.PerRecordFee.Size()
	n += 1 + l + sovCheckpoint(uint64(l))
	if m.MaxRecordsPerCheckpoint != 0 {
		n += 1 + sovCheckpoint(uint64(m.MaxRecordsPerCheckpoint))
	}
	if m.MaxDataPointerBytes != 0 {
		n += 1 + sovCheckpoint(uint64(m.MaxDataPointerBytes))
	}
	return n
}

func sovCheckpoint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCheckpoint(x uint64) (n int) {
	return sovCheckpoint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Checkpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Checkpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Checkpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SidechainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SidechainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousCheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousCheckpointHash = append(m.PreviousCheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousCheckpointHash == nil {
				m.PreviousCheckpointHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordCount", wireType)
			}
			m.RecordCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, &Signature{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
			}
			m.FinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.FinalizedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataPointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Signature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Signature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Signature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerRecordFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PerRecordFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRecordsPerCheckpoint", wireType)
			}
			m.MaxRecordsPerCheckpoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRecordsPerCheckpoint |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDataPointerBytes", wireType)
			}
			m.MaxDataPointerBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDataPointerBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCheckpoint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCheckpoint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCheckpoint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCheckpoint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCheckpoint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCheckpoint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCheckpoint = fmt.Errorf("proto: unexpected end of group")
)
