// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lucidchain/checkpoint/v1/checkpoint.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Checkpoint is a finalized commitment submitted by a registered sidechain.
// It stores only cryptographic commitments -- never raw application data.
type Checkpoint struct {
	// ID of the sidechain this checkpoint belongs to (see x/sidechain.Sidechain.id).
	SidechainId string `protobuf:"bytes,1,opt,name=sidechain_id,json=sidechainId,proto3" json:"sidechain_id,omitempty"`
	// Monotonically increasing lc_sequence number for this sidechain's checkpoints.
	// Must equal the previous checkpoint's lc_sequence + 1 (no gaps, no reordering).
	LcSequence uint64 `protobuf:"varint,2,opt,name=lc_sequence,json=lcSequence,proto3" json:"lc_sequence,omitempty"`
	// Merkle root (or equivalent state commitment) of the batch of records
	// this checkpoint covers, as computed off-chain by the sidechain.
	StateRoot []byte `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// Hash of the immediately preceding checkpoint for this sidechain,
	// forming a verifiable chain. Empty for lc_sequence == 1.
	PreviousCheckpointHash []byte `protobuf:"bytes,4,opt,name=previous_checkpoint_hash,json=previousCheckpointHash,proto3" json:"previous_checkpoint_hash,omitempty"`
	// Number of individual records/events committed in this batch.
	// Informational; used for fee calculation and monitoring, not consensus-critical.
	RecordCount uint64 `protobuf:"varint,5,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	// SHA-256 over the sign bytes of CheckpointSignDoc (see below).
	CheckpointHash []byte `protobuf:"bytes,6,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	// Sidechain.signer_set_version under which this checkpoint was verified.
	SignerSetVersion uint64 `protobuf:"varint,7,opt,name=signer_set_version,json=signerSetVersion,proto3" json:"signer_set_version,omitempty"`
	// Bit i set => the key at Sidechain.signer_keys[i] (at signer_set_version)
	// produced a valid signature. Length = ceil(len(signer_keys) / 8).
	SignerBitmap []byte `protobuf:"bytes,8,opt,name=signer_bitmap,json=signerBitmap,proto3" json:"signer_bitmap,omitempty"`
	// SHA-256 of the concatenation of the verified signatures, ordered by
	// signer_index. Lets an auditor holding the original signatures prove they
	// are the ones the chain accepted, without storing ~3.3 KB per signer.
	SignaturesDigest []byte    `protobuf:"bytes,9,opt,name=signatures_digest,json=signaturesDigest,proto3" json:"signatures_digest,omitempty"`
	FinalizedHeight  int64     `protobuf:"varint,10,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	FinalizedAt      time.Time `protobuf:"bytes,11,opt,name=finalized_at,json=finalizedAt,proto3,stdtime" json:"finalized_at"`
	// Optional off-chain pointer (IPFS CID, URI). Covered by the signatures, not verified on-chain.
	DataPointer string `protobuf:"bytes,12,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9aa1a54f4e494a2, []int{0}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetSidechainId() string {
	if m != nil {
		return m.SidechainId
	}
	return ""
}

func (m *Checkpoint) GetLcSequence() uint64 {
	if m != nil {
		return m.LcSequence
	}
	return 0
}

func (m *Checkpoint) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *Checkpoint) GetPreviousCheckpointHash() []byte {
	if m != nil {
		return m.PreviousCheckpointHash
	}
	return nil
}

func (m *Checkpoint) GetRecordCount() uint64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *Checkpoint) GetCheckpointHash() []byte {
	if m != nil {
		return m.CheckpointHash
	}
	return nil
}

func (m *Checkpoint) GetSignerSetVersion() uint64 {
	if m != nil {
		return m.SignerSetVersion
	}
	return 0
}

func (m *Checkpoint) GetSignerBitmap() []byte {
	if m != nil {
		return m.SignerBitmap
	}
	return nil
}

func (m *Checkpoint) GetSignaturesDigest() []byte {
	if m != nil {
		return m.SignaturesDigest
	}
	return nil
}

func (m *Checkpoint) GetFinalizedHeight() int64 {
	if m != nil {
		return m.FinalizedHeight
	}
	return 0
}

func (m *Checkpoint) GetFinalizedAt() time.Time {
	if m != nil {
		return m.FinalizedAt
	}
	return time.Time{}
}

func (m *Checkpoint) GetDataPointer() string {
	if m != nil {
		return m.DataPointer
	}
	return ""
}

// Signature is one signer's signature over the checkpoint sign bytes.
type Signature struct {
	// Index into Sidechain.signer_keys at MsgSubmitCheckpoint.signer_set_version.
	SignerIndex uint32 `protobuf:"varint,1,opt,name=signer_index,json=signerIndex,proto3" json:"signer_index,omitempty"`
	// Raw signature. ML-DSA-65 signatures are 3309 bytes.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9aa1a54f4e494a2, []int{1}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return m.Size()
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignerIndex() uint32 {
	if m != nil {
		return m.SignerIndex
	}
	return 0
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// CheckpointSignDoc is the document every signer signs (with a domain prefix).
type CheckpointSignDoc struct {
	ChainId                string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	SidechainId            string `protobuf:"bytes,2,opt,name=sidechain_id,json=sidechainId,proto3" json:"sidechain_id,omitempty"`
	LcSequence             uint64 `protobuf:"varint,3,opt,name=lc_sequence,json=lcSequence,proto3" json:"lc_sequence,omitempty"`
	StateRoot              []byte `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	PreviousCheckpointHash []byte `protobuf:"bytes,5,opt,name=previous_checkpoint_hash,json=previousCheckpointHash,proto3" json:"previous_checkpoint_hash,omitempty"`
	RecordCount            uint64 `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	SignerSetVersion       uint64 `protobuf:"varint,7,opt,name=signer_set_version,json=signerSetVersion,proto3" json:"signer_set_version,omitempty"`
	DataPointer            string `protobuf:"bytes,8,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
}

func (m *CheckpointSignDoc) Reset()         { *m = CheckpointSignDoc{} }
func (m *CheckpointSignDoc) String() string { return proto.CompactTextString(m) }
func (*CheckpointSignDoc) ProtoMessage()    {}
func (*CheckpointSignDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9aa1a54f4e494a2, []int{2}
}
func (m *CheckpointSignDoc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckpointSignDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckpointSignDoc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckpointSignDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointSignDoc.Merge(m, src)
}
func (m *CheckpointSignDoc) XXX_Size() int {
	return m.Size()
}
func (m *CheckpointSignDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointSignDoc.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointSignDoc proto.InternalMessageInfo

func (m *CheckpointSignDoc) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *CheckpointSignDoc) GetSidechainId() string {
	if m != nil {
		return m.SidechainId
	}
	return ""
}

func (m *CheckpointSignDoc) GetLcSequence() uint64 {
	if m != nil {
		return m.LcSequence
	}
	return 0
}

func (m *CheckpointSignDoc) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *CheckpointSignDoc) GetPreviousCheckpointHash() []byte {
	if m != nil {
		return m.PreviousCheckpointHash
	}
	return nil
}

func (m *CheckpointSignDoc) GetRecordCount() uint64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *CheckpointSignDoc) GetSignerSetVersion() uint64 {
	if m != nil {
		return m.SignerSetVersion
	}
	return 0
}

func (m *CheckpointSignDoc) GetDataPointer() string {
	if m != nil {
		return m.DataPointer
	}
	return ""
}

func init() {
	proto.RegisterType((*Checkpoint)(nil), "lucidchain.checkpoint.v1.Checkpoint")
	proto.RegisterType((*Signature)(nil), "lucidchain.checkpoint.v1.Signature")
	proto.RegisterType((*CheckpointSignDoc)(nil), "lucidchain.checkpoint.v1.CheckpointSignDoc")
}

func init() {
	proto.RegisterFile("lucidchain/checkpoint/v1/checkpoint.proto", fileDescriptor_d9aa1a54f4e494a2)
}

var fileDescriptor_d9aa1a54f4e494a2 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0x9b, 0x2e, 0xdb, 0x5a, 0xa7, 0x65, 0x9d, 0x05, 0xc8, 0x54, 0x90, 0x96, 0x72, 0xa0,
	0x13, 0x28, 0x51, 0xe1, 0x82, 0xb8, 0xd1, 0x4d, 0x62, 0x03, 0x0e, 0x28, 0x45, 0x1c, 0xb8, 0x44,
	0x8e, 0xe3, 0x25, 0x16, 0x6d, 0x1c, 0x62, 0xa7, 0xda, 0xf8, 0x15, 0x3b, 0x72, 0xe4, 0x9f, 0x70,
	0xdd, 0x71, 0x47, 0x4e, 0x80, 0xda, 0x0b, 0x3f, 0x03, 0xc5, 0x69, 0x9a, 0xd2, 0x1d, 0xa6, 0xde,
	0xe2, 0xe7, 0x7b, 0xf3, 0xf9, 0xb3, 0xdf, 0x57, 0x06, 0x07, 0xe3, 0x94, 0x30, 0x9f, 0x84, 0x98,
	0x45, 0x36, 0x09, 0x29, 0xf9, 0x1c, 0x73, 0x16, 0x49, 0x7b, 0x3a, 0x58, 0x59, 0x59, 0x71, 0xc2,
	0x25, 0x87, 0xa8, 0x94, 0x5a, 0x2b, 0xc5, 0xe9, 0xa0, 0x7d, 0x3b, 0xe0, 0x01, 0x57, 0x22, 0x3b,
	0xfb, 0xca, 0xf5, 0x6d, 0x93, 0x70, 0x31, 0xe1, 0xc2, 0xf6, 0xb0, 0xa0, 0xf6, 0x74, 0xe0, 0x51,
	0x89, 0x07, 0x36, 0xe1, 0x2c, 0x5a, 0xd4, 0x3b, 0x01, 0xe7, 0xc1, 0x98, 0xda, 0x6a, 0xe5, 0xa5,
	0xa7, 0xb6, 0x64, 0x13, 0x2a, 0x24, 0x9e, 0xc4, 0xb9, 0xa0, 0xf7, 0x4d, 0x07, 0xe0, 0x70, 0xb9,
	0x11, 0x7c, 0x08, 0x1a, 0x82, 0xf9, 0x54, 0x0d, 0xe0, 0x32, 0x1f, 0x69, 0x5d, 0xad, 0x5f, 0x77,
	0x8c, 0x25, 0x3b, 0xf1, 0x61, 0x07, 0x18, 0x63, 0xe2, 0x0a, 0xfa, 0x25, 0xa5, 0x11, 0xa1, 0xa8,
	0xda, 0xd5, 0xfa, 0xba, 0x03, 0xc6, 0x64, 0xb4, 0x20, 0xf0, 0x01, 0x00, 0x42, 0x62, 0x49, 0xdd,
	0x84, 0x73, 0x89, 0xb6, 0xba, 0x5a, 0xbf, 0xe1, 0xd4, 0x15, 0x71, 0x38, 0x97, 0xf0, 0x05, 0x40,
	0x71, 0x42, 0xa7, 0x8c, 0xa7, 0xc2, 0x2d, 0x8f, 0xe8, 0x86, 0x58, 0x84, 0x48, 0x57, 0xe2, 0xbb,
	0x45, 0xbd, 0x1c, 0xec, 0x18, 0x8b, 0x30, 0x1b, 0x2e, 0xa1, 0x84, 0x27, 0xbe, 0x4b, 0x78, 0x1a,
	0x49, 0xb4, 0xad, 0xb6, 0x36, 0x72, 0x76, 0x98, 0x21, 0xf8, 0x18, 0xec, 0xad, 0xf7, 0xdc, 0x51,
	0x3d, 0x6f, 0x91, 0xff, 0x7b, 0x3d, 0x05, 0x50, 0xb0, 0x20, 0xa2, 0x89, 0x2b, 0xa8, 0x74, 0xa7,
	0x34, 0x11, 0x8c, 0x47, 0x68, 0x57, 0x75, 0x6c, 0xe5, 0x95, 0x11, 0x95, 0x1f, 0x73, 0x0e, 0x1f,
	0x81, 0xe6, 0x42, 0xed, 0x31, 0x39, 0xc1, 0x31, 0xaa, 0xa9, 0xa6, 0x8d, 0x1c, 0x0e, 0x15, 0x83,
	0x4f, 0xc0, 0x7e, 0xb6, 0xc6, 0x32, 0x4d, 0xa8, 0x70, 0x7d, 0x16, 0x50, 0x21, 0x51, 0x5d, 0x09,
	0x5b, 0x65, 0xe1, 0x48, 0x71, 0x78, 0x00, 0x5a, 0xa7, 0x2c, 0xc2, 0x63, 0xf6, 0x95, 0xfa, 0x6e,
	0x48, 0x59, 0x10, 0x4a, 0x04, 0xba, 0x5a, 0x7f, 0xcb, 0xd9, 0x5b, 0xf2, 0x63, 0x85, 0xe1, 0x6b,
	0xd0, 0x28, 0xa5, 0x58, 0x22, 0xa3, 0xab, 0xf5, 0x8d, 0x67, 0x6d, 0x2b, 0xb7, 0xd6, 0x2a, 0xac,
	0xb5, 0x3e, 0x14, 0xd6, 0x0e, 0x6b, 0x97, 0xbf, 0x3a, 0x95, 0x8b, 0xdf, 0x1d, 0xcd, 0x31, 0x96,
	0x7f, 0xbe, 0x52, 0xe6, 0xfa, 0x58, 0x62, 0x57, 0xdd, 0x02, 0x4d, 0x50, 0x23, 0x37, 0x37, 0x63,
	0xef, 0x73, 0xf4, 0x52, 0xff, 0xfb, 0xbd, 0xa3, 0xbd, 0xd1, 0x6b, 0xcd, 0xd6, 0x9d, 0xde, 0x3b,
	0x50, 0x1f, 0x15, 0x63, 0xe7, 0xc1, 0x50, 0x37, 0xc0, 0x22, 0x9f, 0x9e, 0xa9, 0x60, 0x34, 0x1d,
	0x23, 0x67, 0x27, 0x19, 0x82, 0xf7, 0x41, 0x7d, 0x79, 0x4c, 0x54, 0x5d, 0xd8, 0x5e, 0x80, 0xde,
	0x8f, 0x2a, 0xd8, 0x2f, 0xfd, 0xcc, 0x1a, 0x1f, 0x71, 0x02, 0xef, 0x81, 0xda, 0x5a, 0xd6, 0x76,
	0x8b, 0x9c, 0xad, 0x47, 0xb1, 0x7a, 0x63, 0x14, 0xb7, 0x6e, 0x88, 0xa2, 0xbe, 0x49, 0x14, 0xb7,
	0x37, 0x8a, 0xe2, 0xce, 0xf5, 0x28, 0x6e, 0x96, 0xb0, 0x75, 0x6f, 0x6a, 0xd7, 0xbc, 0x19, 0xbe,
	0xbd, 0x9c, 0x99, 0xda, 0xd5, 0xcc, 0xd4, 0xfe, 0xcc, 0x4c, 0xed, 0x62, 0x6e, 0x56, 0xae, 0xe6,
	0x66, 0xe5, 0xe7, 0xdc, 0xac, 0x7c, 0x1a, 0x04, 0x4c, 0x86, 0xa9, 0x67, 0x11, 0x3e, 0xb1, 0xd5,
	0x03, 0x12, 0xe3, 0x73, 0x7b, 0xe5, 0xd1, 0x39, 0x5b, 0x7d, 0x76, 0xe4, 0x79, 0x4c, 0x85, 0xb7,
	0xa3, 0x62, 0xf3, 0xfc, 0xdf, 0x00, 0xf9, 0xc9, 0x9f, 0xc1, 0x9c, 0x04, 0x00, 0x00,
}

func (this *Checkpoint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Checkpoint)
	if !ok {
		that2, ok := that.(Checkpoint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SidechainId != that1.SidechainId {
		return false
	}
	if this.LcSequence != that1.LcSequence {
		return false
	}
	if !bytes.Equal(this.StateRoot, that1.StateRoot) {
		return false
	}
	if !bytes.Equal(this.PreviousCheckpointHash, that1.PreviousCheckpointHash) {
		return false
	}
	if this.RecordCount != that1.RecordCount {
		return false
	}
	if !bytes.Equal(this.CheckpointHash, that1.CheckpointHash) {
		return false
	}
	if this.SignerSetVersion != that1.SignerSetVersion {
		return false
	}
	if !bytes.Equal(this.SignerBitmap, that1.SignerBitmap) {
		return false
	}
	if !bytes.Equal(this.SignaturesDigest, that1.SignaturesDigest) {
		return false
	}
	if this.FinalizedHeight != that1.FinalizedHeight {
		return false
	}
	if !this.FinalizedAt.Equal(that1.FinalizedAt) {
		return false
	}
	if this.DataPointer != that1.DataPointer {
		return false
	}
	return true
}
func (m *Checkpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataPointer) > 0 {
		i -= len(m.DataPointer)
		copy(dAtA[i:], m.DataPointer)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.DataPointer)))
		i--
		dAtA[i] = 0x62
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.FinalizedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.FinalizedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCheckpoint(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x5a
	if m.FinalizedHeight != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.FinalizedHeight))
		i--
		dAtA[i] = 0x50
	}
	if len(m.SignaturesDigest) > 0 {
		i -= len(m.SignaturesDigest)
		copy(dAtA[i:], m.SignaturesDigest)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.SignaturesDigest)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SignerBitmap) > 0 {
		i -= len(m.SignerBitmap)
		copy(dAtA[i:], m.SignerBitmap)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.SignerBitmap)))
		i--
		dAtA[i] = 0x42
	}
	if m.SignerSetVersion != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.SignerSetVersion))
		i--
		dAtA[i] = 0x38
	}
	if len(m.CheckpointHash) > 0 {
		i -= len(m.CheckpointHash)
		copy(dAtA[i:], m.CheckpointHash)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.CheckpointHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.RecordCount != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.RecordCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PreviousCheckpointHash) > 0 {
		i -= len(m.PreviousCheckpointHash)
		copy(dAtA[i:], m.PreviousCheckpointHash)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.PreviousCheckpointHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LcSequence != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.LcSequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SidechainId) > 0 {
		i -= len(m.SidechainId)
		copy(dAtA[i:], m.SidechainId)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.SidechainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Signature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Signature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Signature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.SignerIndex != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.SignerIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CheckpointSignDoc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckpointSignDoc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckpointSignDoc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataPointer) > 0 {
		i -= len(m.DataPointer)
		copy(dAtA[i:], m.DataPointer)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.DataPointer)))
		i--
		dAtA[i] = 0x42
	}
	if m.SignerSetVersion != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.SignerSetVersion))
		i--
		dAtA[i] = 0x38
	}
	if m.RecordCount != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.RecordCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PreviousCheckpointHash) > 0 {
		i -= len(m.PreviousCheckpointHash)
		copy(dAtA[i:], m.PreviousCheckpointHash)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.PreviousCheckpointHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.LcSequence != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.LcSequence))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SidechainId) > 0 {
		i -= len(m.SidechainId)
		copy(dAtA[i:], m.SidechainId)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.SidechainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCheckpoint(dAtA []byte, offset int, v uint64) int {
	offset -= sovCheckpoint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Checkpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SidechainId)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.LcSequence != 0 {
		n += 1 + sovCheckpoint(uint64(m.LcSequence))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.PreviousCheckpointHash)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.RecordCount != 0 {
		n += 1 + sovCheckpoint(uint64(m.RecordCount))
	}
	l = len(m.CheckpointHash)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.SignerSetVersion != 0 {
		n += 1 + sovCheckpoint(uint64(m.SignerSetVersion))
	}
	l = len(m.SignerBitmap)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.SignaturesDigest)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.FinalizedHeight != 0 {
		n += 1 + sovCheckpoint(uint64(m.FinalizedHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.FinalizedAt)
	n += 1 + l + sovCheckpoint(uint64(l))
	l = len(m.DataPointer)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *Signature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SignerIndex != 0 {
		n += 1 + sovCheckpoint(uint64(m.SignerIndex))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *CheckpointSignDoc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.SidechainId)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.LcSequence != 0 {
		n += 1 + sovCheckpoint(uint64(m.LcSequence))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.PreviousCheckpointHash)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.RecordCount != 0 {
		n += 1 + sovCheckpoint(uint64(m.RecordCount))
	}
	if m.SignerSetVersion != 0 {
		n += 1 + sovCheckpoint(uint64(m.SignerSetVersion))
	}
	l = len(m.DataPointer)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func sovCheckpoint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCheckpoint(x uint64) (n int) {
	return sovCheckpoint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Checkpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Checkpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Checkpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SidechainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SidechainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcSequence", wireType)
			}
			m.LcSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LcSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousCheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousCheckpointHash = append(m.PreviousCheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousCheckpointHash == nil {
				m.PreviousCheckpointHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordCount", wireType)
			}
			m.RecordCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CheckpointHash = append(m.CheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CheckpointHash == nil {
				m.CheckpointHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerSetVersion", wireType)
			}
			m.SignerSetVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerSetVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerBitmap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerBitmap = append(m.SignerBitmap[:0], dAtA[iNdEx:postIndex]...)
			if m.SignerBitmap == nil {
				m.SignerBitmap = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignaturesDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignaturesDigest = append(m.SignaturesDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.SignaturesDigest == nil {
				m.SignaturesDigest = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
			}
			m.FinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.FinalizedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataPointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Signature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Signature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Signature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerIndex", wireType)
			}
			m.SignerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckpointSignDoc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckpointSignDoc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckpointSignDoc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SidechainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SidechainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcSequence", wireType)
			}
			m.LcSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LcSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousCheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousCheckpointHash = append(m.PreviousCheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousCheckpointHash == nil {
				m.PreviousCheckpointHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordCount", wireType)
			}
			m.RecordCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerSetVersion", wireType)
			}
			m.SignerSetVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerSetVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataPointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCheckpoint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCheckpoint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCheckpoint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCheckpoint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCheckpoint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCheckpoint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCheckpoint = fmt.Errorf("proto: unexpected end of group")
)
