// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lucidchain/checkpoint/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSubmitCheckpoint struct {
	Submitter              string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	SidechainId            string `protobuf:"bytes,2,opt,name=sidechain_id,json=sidechainId,proto3" json:"sidechain_id,omitempty"`
	Sequence               uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	StateRoot              []byte `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	PreviousCheckpointHash []byte `protobuf:"bytes,5,opt,name=previous_checkpoint_hash,json=previousCheckpointHash,proto3" json:"previous_checkpoint_hash,omitempty"`
	RecordCount            uint64 `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	DataPointer            string `protobuf:"bytes,7,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
	// Must equal the sidechain's current signer_set_version, otherwise rejected.
	SignerSetVersion uint64      `protobuf:"varint,8,opt,name=signer_set_version,json=signerSetVersion,proto3" json:"signer_set_version,omitempty"`
	Signatures       []Signature `protobuf:"bytes,9,rep,name=signatures,proto3" json:"signatures"`
}

func (m *MsgSubmitCheckpoint) Reset()         { *m = MsgSubmitCheckpoint{} }
func (m *MsgSubmitCheckpoint) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitCheckpoint) ProtoMessage()    {}
func (*MsgSubmitCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_047eb62d7140d510, []int{0}
}
func (m *MsgSubmitCheckpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitCheckpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitCheckpoint.Merge(m, src)
}
func (m *MsgSubmitCheckpoint) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitCheckpoint proto.InternalMessageInfo

func (m *MsgSubmitCheckpoint) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitCheckpoint) GetSidechainId() string {
	if m != nil {
		return m.SidechainId
	}
	return ""
}

func (m *MsgSubmitCheckpoint) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MsgSubmitCheckpoint) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *MsgSubmitCheckpoint) GetPreviousCheckpointHash() []byte {
	if m != nil {
		return m.PreviousCheckpointHash
	}
	return nil
}

func (m *MsgSubmitCheckpoint) GetRecordCount() uint64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *MsgSubmitCheckpoint) GetDataPointer() string {
	if m != nil {
		return m.DataPointer
	}
	return ""
}

func (m *MsgSubmitCheckpoint) GetSignerSetVersion() uint64 {
	if m != nil {
		return m.SignerSetVersion
	}
	return 0
}

func (m *MsgSubmitCheckpoint) GetSignatures() []Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type MsgSubmitCheckpointResponse struct {
	FinalizedHeight uint64 `protobuf:"varint,1,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	CheckpointHash  []byte `protobuf:"bytes,2,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
}

func (m *MsgSubmitCheckpointResponse) Reset()         { *m = MsgSubmitCheckpointResponse{} }
func (m *MsgSubmitCheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitCheckpointResponse) ProtoMessage()    {}
func (*MsgSubmitCheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_047eb62d7140d510, []int{1}
}
func (m *MsgSubmitCheckpointResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitCheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitCheckpointResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitCheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitCheckpointResponse.Merge(m, src)
}
func (m *MsgSubmitCheckpointResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitCheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitCheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitCheckpointResponse proto.InternalMessageInfo

func (m *MsgSubmitCheckpointResponse) GetFinalizedHeight() uint64 {
	if m != nil {
		return m.FinalizedHeight
	}
	return 0
}

func (m *MsgSubmitCheckpointResponse) GetCheckpointHash() []byte {
	if m != nil {
		return m.CheckpointHash
	}
	return nil
}

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_047eb62d7140d510, []int{2}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_047eb62d7140d510, []int{3}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitCheckpoint)(nil), "lucidchain.checkpoint.v1.MsgSubmitCheckpoint")
	proto.RegisterType((*MsgSubmitCheckpointResponse)(nil), "lucidchain.checkpoint.v1.MsgSubmitCheckpointResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "lucidchain.checkpoint.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "lucidchain.checkpoint.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("lucidchain/checkpoint/v1/tx.proto", fileDescriptor_047eb62d7140d510) }

var fileDescriptor_047eb62d7140d510 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0xb4, 0xf0, 0xa3, 0x53, 0x02, 0xcd, 0xfc, 0x88, 0x0c, 0x55, 0x6b, 0xa9, 0x07,
	0x0b, 0x91, 0x6e, 0x8a, 0xd1, 0x18, 0x0f, 0x26, 0xc2, 0x05, 0x34, 0x24, 0x64, 0x1b, 0x3d, 0x78,
	0xd9, 0x0c, 0xbb, 0xe3, 0xee, 0x44, 0x76, 0x67, 0x99, 0x67, 0xb6, 0x01, 0x2f, 0x1a, 0x5f, 0x81,
	0x2f, 0x85, 0x83, 0x27, 0x5f, 0x01, 0x47, 0xe2, 0xc9, 0x93, 0x31, 0xf4, 0xc0, 0x1b, 0xf0, 0x05,
	0x98, 0x9d, 0xdd, 0xee, 0x16, 0xa4, 0x46, 0x6f, 0x3b, 0xdf, 0xe7, 0xf3, 0xfc, 0xfb, 0xce, 0x66,
	0xd0, 0xca, 0x41, 0xec, 0x70, 0xd7, 0xf1, 0x29, 0x0f, 0x4d, 0xc7, 0x67, 0xce, 0xdb, 0x48, 0xf0,
	0x50, 0x99, 0x83, 0x9e, 0xa9, 0x8e, 0xba, 0x91, 0x14, 0x4a, 0x60, 0x52, 0x20, 0xdd, 0x02, 0xe9,
	0x0e, 0x7a, 0x8d, 0x45, 0x4f, 0x78, 0x42, 0x43, 0x66, 0xf2, 0x95, 0xf2, 0x8d, 0x65, 0x47, 0x40,
	0x20, 0xc0, 0x4e, 0x03, 0xe9, 0x21, 0x0b, 0x2d, 0xa5, 0x27, 0x33, 0x00, 0x2f, 0x69, 0x11, 0x80,
	0x97, 0x05, 0x56, 0x27, 0x8e, 0x31, 0xd6, 0x51, 0xa3, 0xed, 0x2f, 0x65, 0xf4, 0xff, 0x2e, 0x78,
	0xfd, 0x78, 0x3f, 0xe0, 0x6a, 0x2b, 0x8f, 0xe2, 0x47, 0xa8, 0x0a, 0x5a, 0x53, 0x4c, 0x12, 0xa3,
	0x65, 0x74, 0xaa, 0x9b, 0xe4, 0xeb, 0xe7, 0xf5, 0xc5, 0x6c, 0x80, 0x67, 0xae, 0x2b, 0x19, 0x40,
	0x5f, 0x49, 0x1e, 0x7a, 0x56, 0x81, 0xe2, 0x15, 0x34, 0x07, 0xdc, 0x65, 0xba, 0xb7, 0xcd, 0x5d,
	0x32, 0x95, 0xa4, 0x5a, 0xb5, 0x5c, 0xdb, 0x71, 0x71, 0x03, 0xcd, 0x02, 0x3b, 0x8c, 0x59, 0xe8,
	0x30, 0x52, 0x6e, 0x19, 0x9d, 0x8a, 0x95, 0x9f, 0xf1, 0x6d, 0x84, 0x40, 0x51, 0xc5, 0x6c, 0x29,
	0x84, 0x22, 0x95, 0x96, 0xd1, 0x99, 0xb3, 0xaa, 0x5a, 0xb1, 0x84, 0x50, 0xf8, 0x31, 0x22, 0x91,
	0x64, 0x03, 0x2e, 0x62, 0xb0, 0x8b, 0x55, 0x6c, 0x9f, 0x82, 0x4f, 0xa6, 0x35, 0x7c, 0x63, 0x14,
	0x2f, 0x76, 0xd9, 0xa6, 0xe0, 0x27, 0x73, 0x49, 0xe6, 0x08, 0xe9, 0xda, 0x8e, 0x88, 0x43, 0x45,
	0x66, 0x74, 0xe3, 0x5a, 0xaa, 0x6d, 0x25, 0x52, 0x82, 0xb8, 0x54, 0x51, 0x5b, 0x27, 0x31, 0x49,
	0xfe, 0x4b, 0x47, 0x4f, 0xb4, 0xbd, 0x54, 0xc2, 0xf7, 0x11, 0x06, 0xee, 0x85, 0x4c, 0xda, 0xc0,
	0x94, 0x3d, 0x60, 0x12, 0xb8, 0x08, 0xc9, 0xac, 0xae, 0x55, 0x4f, 0x23, 0x7d, 0xa6, 0x5e, 0xa5,
	0x3a, 0xde, 0x41, 0x28, 0xd1, 0xa8, 0x8a, 0x25, 0x03, 0x52, 0x6d, 0x95, 0x3b, 0xb5, 0x8d, 0xbb,
	0xdd, 0x49, 0xf7, 0xdf, 0xed, 0x8f, 0xd8, 0xcd, 0xca, 0xe9, 0xf7, 0x3b, 0x25, 0x6b, 0x2c, 0xf9,
	0xc9, 0xfc, 0xc7, 0x8b, 0x93, 0xb5, 0xc2, 0xe6, 0xe7, 0x95, 0x59, 0x54, 0xaf, 0xb7, 0x0f, 0xd1,
	0xcd, 0x6b, 0xee, 0xce, 0x62, 0x10, 0x89, 0x10, 0x18, 0x5e, 0x45, 0xf5, 0x37, 0x3c, 0xa4, 0x07,
	0xfc, 0x1d, 0x73, 0x6d, 0x9f, 0x71, 0xcf, 0x57, 0xfa, 0x2a, 0x2b, 0xd6, 0x42, 0xae, 0x6f, 0x6b,
	0x19, 0xdf, 0x43, 0x0b, 0x57, 0xfd, 0x9c, 0xd2, 0x7e, 0xce, 0x3b, 0x97, 0x7c, 0x6c, 0xbf, 0x47,
	0x0b, 0xbb, 0xe0, 0xbd, 0x8c, 0x5c, 0xaa, 0xd8, 0x1e, 0x95, 0x34, 0x00, 0x7c, 0x0b, 0x55, 0x69,
	0xac, 0x7c, 0x21, 0xb9, 0x3a, 0x4e, 0x7f, 0x15, 0xab, 0x10, 0xf0, 0x53, 0x34, 0x13, 0x69, 0x4e,
	0x17, 0xac, 0x6d, 0xb4, 0x26, 0x1b, 0x90, 0xd6, 0xcb, 0xb6, 0xcf, 0xb2, 0xb2, 0xcd, 0xf3, 0x7a,
	0xed, 0x65, 0xb4, 0x74, 0x65, 0x80, 0xd1, 0xbe, 0x1b, 0x3f, 0x0d, 0x54, 0xde, 0x05, 0x0f, 0x1f,
	0xa1, 0xfa, 0x6f, 0xff, 0xf3, 0xfa, 0xe4, 0xb6, 0xd7, 0x58, 0xd8, 0x78, 0xf8, 0x4f, 0x78, 0xee,
	0xf8, 0x01, 0x9a, 0xbb, 0x64, 0xcd, 0xea, 0x1f, 0xcb, 0x8c, 0xa3, 0x8d, 0xde, 0x5f, 0xa3, 0xa3,
	0x6e, 0x8d, 0xe9, 0x0f, 0x17, 0x27, 0x6b, 0xc6, 0xe6, 0x8b, 0xd3, 0xf3, 0xa6, 0x71, 0x76, 0xde,
	0x34, 0x7e, 0x9c, 0x37, 0x8d, 0x4f, 0xc3, 0x66, 0xe9, 0x6c, 0xd8, 0x2c, 0x7d, 0x1b, 0x36, 0x4b,
	0xaf, 0x7b, 0x1e, 0x57, 0x7e, 0xbc, 0xdf, 0x75, 0x44, 0x60, 0xea, 0xea, 0x11, 0x3d, 0x36, 0xc7,
	0xde, 0x86, 0xa3, 0xf1, 0xd7, 0x41, 0x1d, 0x47, 0x0c, 0xf6, 0x67, 0xf4, 0xb3, 0xf0, 0xe0, 0xd7,
	0x00, 0x42, 0x97, 0x97, 0xb1, 0xca, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitCheckpoint submits a new, signed checkpoint for a registered, active sidechain.
	SubmitCheckpoint(ctx context.Context, in *MsgSubmitCheckpoint, opts ...grpc.CallOption) (*MsgSubmitCheckpointResponse, error)
	// UpdateParams updates module parameters via governance.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitCheckpoint(ctx context.Context, in *MsgSubmitCheckpoint, opts ...grpc.CallOption) (*MsgSubmitCheckpointResponse, error) {
	out := new(MsgSubmitCheckpointResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.checkpoint.v1.Msg/SubmitCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.checkpoint.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitCheckpoint submits a new, signed checkpoint for a registered, active sidechain.
	SubmitCheckpoint(context.Context, *MsgSubmitCheckpoint) (*MsgSubmitCheckpointResponse, error)
	// UpdateParams updates module parameters via governance.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitCheckpoint(ctx context.Context, req *MsgSubmitCheckpoint) (*MsgSubmitCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCheckpoint not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitCheckpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.checkpoint.v1.Msg/SubmitCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitCheckpoint(ctx, req.(*MsgSubmitCheckpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.checkpoint.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lucidchain.checkpoint.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCheckpoint",
			Handler:    _Msg_SubmitCheckpoint_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lucidchain/checkpoint/v1/tx.proto",
}

func (m *MsgSubmitCheckpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitCheckpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitCheckpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.SignerSetVersion != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignerSetVersion))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DataPointer) > 0 {
		i -= len(m.DataPointer)
		copy(dAtA[i:], m.DataPointer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DataPointer)))
		i--
		dAtA[i] = 0x3a
	}
	if m.RecordCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RecordCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PreviousCheckpointHash) > 0 {
		i -= len(m.PreviousCheckpointHash)
		copy(dAtA[i:], m.PreviousCheckpointHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PreviousCheckpointHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SidechainId) > 0 {
		i -= len(m.SidechainId)
		copy(dAtA[i:], m.SidechainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SidechainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitCheckpointResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitCheckpointResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitCheckpointResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CheckpointHash) > 0 {
		i -= len(m.CheckpointHash)
		copy(dAtA[i:], m.CheckpointHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CheckpointHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.FinalizedHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FinalizedHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitCheckpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SidechainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PreviousCheckpointHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RecordCount != 0 {
		n += 1 + sovTx(uint64(m.RecordCount))
	}
	l = len(m.DataPointer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SignerSetVersion != 0 {
		n += 1 + sovTx(uint64(m.SignerSetVersion))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitCheckpointResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FinalizedHeight != 0 {
		n += 1 + sovTx(uint64(m.FinalizedHeight))
	}
	l = len(m.CheckpointHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitCheckpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitCheckpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitCheckpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SidechainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SidechainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousCheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousCheckpointHash = append(m.PreviousCheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousCheckpointHash == nil {
				m.PreviousCheckpointHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordCount", wireType)
			}
			m.RecordCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataPointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerSetVersion", wireType)
			}
			m.SignerSetVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerSetVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, Signature{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitCheckpointResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitCheckpointResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitCheckpointResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
			}
			m.FinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CheckpointHash = append(m.CheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CheckpointHash == nil {
				m.CheckpointHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
