// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lucidchain/sidechain/v1/sidechain.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	any "github.com/cosmos/gogoproto/types/any"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AssuranceTier defines the level of validation a sidechain has registered for.
type AssuranceTier int32

const (
	AssuranceTier_ASSURANCE_TIER_UNSPECIFIED AssuranceTier = 0
	AssuranceTier_ASSURANCE_TIER_NOTARIZED   AssuranceTier = 1
	AssuranceTier_ASSURANCE_TIER_ATTESTED    AssuranceTier = 2
	AssuranceTier_ASSURANCE_TIER_PROVEN      AssuranceTier = 3
)

var AssuranceTier_name = map[int32]string{
	0: "ASSURANCE_TIER_UNSPECIFIED",
	1: "ASSURANCE_TIER_NOTARIZED",
	2: "ASSURANCE_TIER_ATTESTED",
	3: "ASSURANCE_TIER_PROVEN",
}

var AssuranceTier_value = map[string]int32{
	"ASSURANCE_TIER_UNSPECIFIED": 0,
	"ASSURANCE_TIER_NOTARIZED":   1,
	"ASSURANCE_TIER_ATTESTED":    2,
	"ASSURANCE_TIER_PROVEN":      3,
}

func (x AssuranceTier) String() string {
	return proto.EnumName(AssuranceTier_name, int32(x))
}

func (AssuranceTier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c45b503e7869a91a, []int{0}
}

// SidechainStatus defines the lifecycle state of a registered sidechain.
type SidechainStatus int32

const (
	SidechainStatus_SIDECHAIN_STATUS_UNSPECIFIED SidechainStatus = 0
	SidechainStatus_SIDECHAIN_STATUS_PENDING     SidechainStatus = 1
	SidechainStatus_SIDECHAIN_STATUS_ACTIVE      SidechainStatus = 2
	SidechainStatus_SIDECHAIN_STATUS_SUSPENDED   SidechainStatus = 3
	SidechainStatus_SIDECHAIN_STATUS_SLASHED     SidechainStatus = 4
	SidechainStatus_SIDECHAIN_STATUS_EXITED      SidechainStatus = 5
)

var SidechainStatus_name = map[int32]string{
	0: "SIDECHAIN_STATUS_UNSPECIFIED",
	1: "SIDECHAIN_STATUS_PENDING",
	2: "SIDECHAIN_STATUS_ACTIVE",
	3: "SIDECHAIN_STATUS_SUSPENDED",
	4: "SIDECHAIN_STATUS_SLASHED",
	5: "SIDECHAIN_STATUS_EXITED",
}

var SidechainStatus_value = map[string]int32{
	"SIDECHAIN_STATUS_UNSPECIFIED": 0,
	"SIDECHAIN_STATUS_PENDING":     1,
	"SIDECHAIN_STATUS_ACTIVE":      2,
	"SIDECHAIN_STATUS_SUSPENDED":   3,
	"SIDECHAIN_STATUS_SLASHED":     4,
	"SIDECHAIN_STATUS_EXITED":      5,
}

func (x SidechainStatus) String() string {
	return proto.EnumName(SidechainStatus_name, int32(x))
}

func (SidechainStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c45b503e7869a91a, []int{1}
}

// Sidechain is the on-chain registration record for a private sidechain.
type Sidechain struct {
	// Unique identifier, assigned at registration (e.g. "hospitality-platform-01").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name, shown in explorers and dashboards.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Bech32 address of the sidechain operator (registration owner, admin actions).
	Operator string `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	// Keys authorized to sign checkpoints, as SDK public keys. Post-quantum
	// deployments use /cosmos.crypto.mldsa65.PubKey (ML-DSA-65, FIPS 204).
	// Allowed type URLs are restricted by Params.allowed_pubkey_type_urls.
	// Order is significant: Signature.signer_index refers to a position in this list.
	SignerKeys []*any.Any `protobuf:"bytes,4,rep,name=signer_keys,json=signerKeys,proto3" json:"signer_keys,omitempty"`
	// Minimum number of distinct signers required per checkpoint.
	SignatureThreshold uint32 `protobuf:"varint,5,opt,name=signature_threshold,json=signatureThreshold,proto3" json:"signature_threshold,omitempty"`
	// Incremented on every change to signer_keys or signature_threshold.
	// Checkpoints record the version they were signed under, so signer indices
	// stay unambiguous across rotations.
	SignerSetVersion uint64          `protobuf:"varint,6,opt,name=signer_set_version,json=signerSetVersion,proto3" json:"signer_set_version,omitempty"`
	Tier             AssuranceTier   `protobuf:"varint,7,opt,name=tier,proto3,enum=lucidchain.sidechain.v1.AssuranceTier" json:"tier,omitempty"`
	Status           SidechainStatus `protobuf:"varint,8,opt,name=status,proto3,enum=lucidchain.sidechain.v1.SidechainStatus" json:"status,omitempty"`
	// Bond posted at registration (amount and denom).
	Bond types.Coin `protobuf:"bytes,9,opt,name=bond,proto3" json:"bond"`
	// Expected interval between checkpoints, in seconds.
	CheckpointIntervalSeconds uint64 `protobuf:"varint,10,opt,name=checkpoint_interval_seconds,json=checkpointIntervalSeconds,proto3" json:"checkpoint_interval_seconds,omitempty"`
	// Owned by x/sidechain; updated by x/checkpoint via the expected-keeper call
	// RecordCheckpoint. Zero / empty until the first checkpoint is accepted.
	LastCheckpointSequence uint64     `protobuf:"varint,11,opt,name=last_checkpoint_sequence,json=lastCheckpointSequence,proto3" json:"last_checkpoint_sequence,omitempty"`
	LastCheckpointHeight   int64      `protobuf:"varint,12,opt,name=last_checkpoint_height,json=lastCheckpointHeight,proto3" json:"last_checkpoint_height,omitempty"`
	LastCheckpointHash     []byte     `protobuf:"bytes,13,opt,name=last_checkpoint_hash,json=lastCheckpointHash,proto3" json:"last_checkpoint_hash,omitempty"`
	RegisteredAt           time.Time  `protobuf:"bytes,14,opt,name=registered_at,json=registeredAt,proto3,stdtime" json:"registered_at"`
	LastCheckpointAt       *time.Time `protobuf:"bytes,15,opt,name=last_checkpoint_at,json=lastCheckpointAt,proto3,stdtime" json:"last_checkpoint_at,omitempty"`
	// Set by InitiateExit.
	ExitRequestedAt *time.Time `protobuf:"bytes,16,opt,name=exit_requested_at,json=exitRequestedAt,proto3,stdtime" json:"exit_requested_at,omitempty"`
	BondReturnAt    *time.Time `protobuf:"bytes,17,opt,name=bond_return_at,json=bondReturnAt,proto3,stdtime" json:"bond_return_at,omitempty"`
	// Off-chain metadata document URI.
	MetadataUri string `protobuf:"bytes,18,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
}

func (m *Sidechain) Reset()         { *m = Sidechain{} }
func (m *Sidechain) String() string { return proto.CompactTextString(m) }
func (*Sidechain) ProtoMessage()    {}
func (*Sidechain) Descriptor() ([]byte, []int) {
	return fileDescriptor_c45b503e7869a91a, []int{0}
}
func (m *Sidechain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sidechain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sidechain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sidechain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sidechain.Merge(m, src)
}
func (m *Sidechain) XXX_Size() int {
	return m.Size()
}
func (m *Sidechain) XXX_DiscardUnknown() {
	xxx_messageInfo_Sidechain.DiscardUnknown(m)
}

var xxx_messageInfo_Sidechain proto.InternalMessageInfo

func (m *Sidechain) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sidechain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sidechain) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Sidechain) GetSignerKeys() []*any.Any {
	if m != nil {
		return m.SignerKeys
	}
	return nil
}

func (m *Sidechain) GetSignatureThreshold() uint32 {
	if m != nil {
		return m.SignatureThreshold
	}
	return 0
}

func (m *Sidechain) GetSignerSetVersion() uint64 {
	if m != nil {
		return m.SignerSetVersion
	}
	return 0
}

func (m *Sidechain) GetTier() AssuranceTier {
	if m != nil {
		return m.Tier
	}
	return AssuranceTier_ASSURANCE_TIER_UNSPECIFIED
}

func (m *Sidechain) GetStatus() SidechainStatus {
	if m != nil {
		return m.Status
	}
	return SidechainStatus_SIDECHAIN_STATUS_UNSPECIFIED
}

func (m *Sidechain) GetBond() types.Coin {
	if m != nil {
		return m.Bond
	}
	return types.Coin{}
}

func (m *Sidechain) GetCheckpointIntervalSeconds() uint64 {
	if m != nil {
		return m.CheckpointIntervalSeconds
	}
	return 0
}

func (m *Sidechain) GetLastCheckpointSequence() uint64 {
	if m != nil {
		return m.LastCheckpointSequence
	}
	return 0
}

func (m *Sidechain) GetLastCheckpointHeight() int64 {
	if m != nil {
		return m.LastCheckpointHeight
	}
	return 0
}

func (m *Sidechain) GetLastCheckpointHash() []byte {
	if m != nil {
		return m.LastCheckpointHash
	}
	return nil
}

func (m *Sidechain) GetRegisteredAt() time.Time {
	if m != nil {
		return m.RegisteredAt
	}
	return time.Time{}
}

func (m *Sidechain) GetLastCheckpointAt() *time.Time {
	if m != nil {
		return m.LastCheckpointAt
	}
	return nil
}

func (m *Sidechain) GetExitRequestedAt() *time.Time {
	if m != nil {
		return m.ExitRequestedAt
	}
	return nil
}

func (m *Sidechain) GetBondReturnAt() *time.Time {
	if m != nil {
		return m.BondReturnAt
	}
	return nil
}

func (m *Sidechain) GetMetadataUri() string {
	if m != nil {
		return m.MetadataUri
	}
	return ""
}

func init() {
	proto.RegisterEnum("lucidchain.sidechain.v1.AssuranceTier", AssuranceTier_name, AssuranceTier_value)
	proto.RegisterEnum("lucidchain.sidechain.v1.SidechainStatus", SidechainStatus_name, SidechainStatus_value)
	proto.RegisterType((*Sidechain)(nil), "lucidchain.sidechain.v1.Sidechain")
}

func init() {
	proto.RegisterFile("lucidchain/sidechain/v1/sidechain.proto", fileDescriptor_c45b503e7869a91a)
}

var fileDescriptor_c45b503e7869a91a = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xc1, 0x6e, 0xdb, 0x36,
	0x18, 0xc7, 0x23, 0xdb, 0x4d, 0x13, 0xda, 0x49, 0x54, 0xce, 0x6b, 0x69, 0xb7, 0x70, 0xbc, 0x1d,
	0x36, 0xa3, 0xd8, 0xa4, 0x26, 0xdd, 0x61, 0xe8, 0x61, 0x98, 0x62, 0x6b, 0x8b, 0xda, 0xc1, 0x31,
	0x24, 0x39, 0x18, 0x7a, 0x11, 0x68, 0x89, 0xb3, 0x88, 0xda, 0xa2, 0x47, 0x52, 0x46, 0xfd, 0x00,
	0xbb, 0xf7, 0x11, 0xf6, 0x10, 0x7b, 0x88, 0x6e, 0xa7, 0x1e, 0x77, 0xda, 0x86, 0xe4, 0xb2, 0x27,
	0xd8, 0x79, 0x10, 0x25, 0xc7, 0x89, 0xdd, 0x02, 0xed, 0x8d, 0x1f, 0x7f, 0xff, 0xff, 0xa7, 0x8f,
	0xdf, 0x47, 0x49, 0xe0, 0xf3, 0x49, 0x1a, 0xd2, 0x28, 0x8c, 0x31, 0x4d, 0x4c, 0x41, 0x23, 0x92,
	0xaf, 0xe6, 0x47, 0xab, 0xc0, 0x98, 0x71, 0x26, 0x19, 0xbc, 0xb7, 0x12, 0x1a, 0x2b, 0x36, 0x3f,
	0x6a, 0xd6, 0xc7, 0x6c, 0xcc, 0x94, 0xc6, 0xcc, 0x56, 0xb9, 0xbc, 0xd9, 0x08, 0x99, 0x98, 0x32,
	0x11, 0xe4, 0x20, 0x0f, 0x0a, 0xd4, 0xca, 0x23, 0x73, 0x84, 0x05, 0x31, 0xe7, 0x47, 0x23, 0x22,
	0xf1, 0x91, 0x19, 0xb2, 0xe5, 0x93, 0x9a, 0x8d, 0x31, 0x63, 0xe3, 0x09, 0x31, 0x55, 0x34, 0x4a,
	0x7f, 0x32, 0x71, 0xb2, 0x28, 0xd0, 0xe1, 0x3a, 0x92, 0x74, 0x4a, 0x84, 0xc4, 0xd3, 0x59, 0x2e,
	0xf8, 0xf4, 0xbf, 0xdb, 0x60, 0xd7, 0x5b, 0x56, 0x07, 0xf7, 0x41, 0x89, 0x46, 0x48, 0x6b, 0x6b,
	0x9d, 0x5d, 0xb7, 0x44, 0x23, 0x08, 0x41, 0x25, 0xc1, 0x53, 0x82, 0x4a, 0x6a, 0x47, 0xad, 0x61,
	0x13, 0xec, 0xb0, 0x19, 0xe1, 0x58, 0x32, 0x8e, 0xca, 0x6a, 0xff, 0x2a, 0x86, 0x67, 0xa0, 0x2a,
	0xe8, 0x38, 0x21, 0x3c, 0x78, 0x41, 0x16, 0x02, 0x55, 0xda, 0xe5, 0x4e, 0xf5, 0xb8, 0x6e, 0xe4,
	0x45, 0x18, 0xcb, 0x22, 0x0c, 0x2b, 0x59, 0x9c, 0xa0, 0x3f, 0x7e, 0xfb, 0xb2, 0x5e, 0x1c, 0x33,
	0xe4, 0x8b, 0x99, 0x64, 0xc6, 0x20, 0x1d, 0x3d, 0x23, 0x0b, 0x17, 0xe4, 0x29, 0x9e, 0x91, 0x85,
	0x80, 0x26, 0xf8, 0x28, 0x8b, 0xb0, 0x4c, 0x39, 0x09, 0x64, 0xcc, 0x89, 0x88, 0xd9, 0x24, 0x42,
	0xb7, 0xda, 0x5a, 0x67, 0xcf, 0x85, 0x57, 0xc8, 0x5f, 0x12, 0xf8, 0x05, 0x80, 0x45, 0x05, 0x82,
	0xc8, 0x60, 0x4e, 0xb8, 0xa0, 0x2c, 0x41, 0xdb, 0x6d, 0xad, 0x53, 0x71, 0xf5, 0x9c, 0x78, 0x44,
	0x9e, 0xe7, 0xfb, 0xf0, 0x09, 0xa8, 0x48, 0x4a, 0x38, 0xba, 0xdd, 0xd6, 0x3a, 0xfb, 0xc7, 0x9f,
	0x19, 0xef, 0x18, 0x99, 0x61, 0x09, 0x91, 0x72, 0x9c, 0x84, 0xc4, 0xa7, 0x84, 0xbb, 0xca, 0x03,
	0xbf, 0x05, 0xdb, 0x42, 0x62, 0x99, 0x0a, 0xb4, 0xa3, 0xdc, 0x9d, 0x77, 0xba, 0xaf, 0xfa, 0xeb,
	0x29, 0xbd, 0x5b, 0xf8, 0xe0, 0x63, 0x50, 0x19, 0xb1, 0x24, 0x42, 0xbb, 0x6d, 0xad, 0x53, 0x3d,
	0x6e, 0x18, 0x45, 0x37, 0xb2, 0x31, 0x1b, 0xc5, 0x98, 0x8d, 0x2e, 0xa3, 0xc9, 0x49, 0xe5, 0xf5,
	0x5f, 0x87, 0x5b, 0xae, 0x12, 0xc3, 0x6f, 0xc0, 0xfd, 0x30, 0x26, 0xe1, 0x8b, 0x19, 0xa3, 0x89,
	0x0c, 0x68, 0x22, 0x09, 0x9f, 0xe3, 0x49, 0x20, 0x48, 0xc8, 0x92, 0x48, 0x20, 0xa0, 0x4e, 0xda,
	0x58, 0x49, 0x9c, 0x42, 0xe1, 0xe5, 0x02, 0xf8, 0x35, 0x40, 0x13, 0x2c, 0x64, 0x70, 0x2d, 0x89,
	0x20, 0x3f, 0xa7, 0x24, 0x09, 0x09, 0xaa, 0x2a, 0xf3, 0xdd, 0x8c, 0x77, 0xaf, 0xb0, 0x57, 0x50,
	0xf8, 0x15, 0xb8, 0xbb, 0xee, 0x8c, 0x09, 0x1d, 0xc7, 0x12, 0xd5, 0xda, 0x5a, 0xa7, 0xec, 0xd6,
	0x6f, 0xfa, 0x4e, 0x15, 0x83, 0x8f, 0x40, 0x7d, 0xc3, 0x85, 0x45, 0x8c, 0xf6, 0xda, 0x5a, 0xa7,
	0xe6, 0xc2, 0x35, 0x0f, 0x16, 0x31, 0x74, 0xc0, 0x1e, 0x27, 0x63, 0x2a, 0x24, 0xe1, 0x24, 0x0a,
	0xb0, 0x44, 0xfb, 0xaa, 0x3f, 0xcd, 0x8d, 0x6b, 0xe4, 0x2f, 0xef, 0xf2, 0xc9, 0x4e, 0xd6, 0xa0,
	0x57, 0x7f, 0x1f, 0x6a, 0x6e, 0x6d, 0x65, 0xb5, 0x24, 0x74, 0x01, 0x5c, 0x7f, 0x38, 0x96, 0xe8,
	0xe0, 0xbd, 0xf2, 0x69, 0x2a, 0x9f, 0x7e, 0xb3, 0x40, 0x4b, 0xc2, 0x01, 0xb8, 0x43, 0x5e, 0x52,
	0x19, 0xf0, 0xac, 0x2f, 0x42, 0xe6, 0x25, 0xea, 0x1f, 0x90, 0xf2, 0x20, 0xb3, 0xbb, 0x4b, 0xb7,
	0x25, 0xe1, 0x53, 0xb0, 0x9f, 0x8d, 0x36, 0xe0, 0x44, 0xa6, 0x3c, 0xc9, 0xd2, 0xdd, 0xf9, 0x80,
	0x74, 0xb5, 0xcc, 0xeb, 0x2a, 0xab, 0x25, 0xe1, 0x27, 0xa0, 0x36, 0x25, 0x12, 0x47, 0x58, 0xe2,
	0x20, 0xe5, 0x14, 0x41, 0xf5, 0x86, 0x56, 0x97, 0x7b, 0x43, 0x4e, 0x9f, 0x54, 0xfe, 0xfd, 0xf5,
	0x50, 0x7b, 0xf8, 0x8b, 0x06, 0xf6, 0x6e, 0x5c, 0x6b, 0xd8, 0x02, 0x4d, 0xcb, 0xf3, 0x86, 0xae,
	0xd5, 0xef, 0xda, 0x81, 0xef, 0xd8, 0x6e, 0x30, 0xec, 0x7b, 0x03, 0xbb, 0xeb, 0x7c, 0xe7, 0xd8,
	0x3d, 0x7d, 0x0b, 0x3e, 0x00, 0x68, 0x8d, 0xf7, 0xcf, 0x7c, 0xcb, 0x75, 0x9e, 0xdb, 0x3d, 0x5d,
	0x83, 0xf7, 0xc1, 0xbd, 0x35, 0x6a, 0xf9, 0xbe, 0xed, 0xf9, 0x76, 0x4f, 0x2f, 0xc1, 0x06, 0xf8,
	0x78, 0x0d, 0x0e, 0xdc, 0xb3, 0x73, 0xbb, 0xaf, 0x97, 0x1f, 0xfe, 0xae, 0x81, 0x83, 0xb5, 0x17,
	0x04, 0xb6, 0xc1, 0x03, 0xcf, 0xe9, 0xd9, 0xdd, 0x53, 0xcb, 0xe9, 0x07, 0x9e, 0x6f, 0xf9, 0x43,
	0x6f, 0xb3, 0x96, 0x0d, 0xc5, 0xc0, 0xee, 0xf7, 0x9c, 0xfe, 0xf7, 0x79, 0x2d, 0x1b, 0xd4, 0xea,
	0xfa, 0xce, 0xb9, 0xad, 0x97, 0xb2, 0x63, 0x6e, 0x40, 0x6f, 0xe8, 0x65, 0x6e, 0xbb, 0xa7, 0x97,
	0xdf, 0x9a, 0xda, 0xfb, 0xc1, 0xf2, 0x4e, 0xed, 0x9e, 0x5e, 0x79, 0x6b, 0x6a, 0xfb, 0x47, 0x27,
	0x3b, 0xe6, 0xad, 0x93, 0xa7, 0xaf, 0x2f, 0x5a, 0xda, 0x9b, 0x8b, 0x96, 0xf6, 0xcf, 0x45, 0x4b,
	0x7b, 0x75, 0xd9, 0xda, 0x7a, 0x73, 0xd9, 0xda, 0xfa, 0xf3, 0xb2, 0xb5, 0xf5, 0xfc, 0xd1, 0x98,
	0xca, 0x38, 0x1d, 0x19, 0x21, 0x9b, 0x9a, 0xea, 0x33, 0x31, 0xc3, 0x0b, 0xf3, 0xda, 0x9f, 0xe4,
	0xe5, 0xb5, 0x7f, 0x89, 0x5c, 0xcc, 0x88, 0x18, 0x6d, 0xab, 0xa1, 0x3f, 0xfe, 0x7f, 0x00, 0x3b,
	0x66, 0x6c, 0x36, 0x70, 0x06, 0x00, 0x00,
}

func (this *Sidechain) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Sidechain)
	if !ok {
		that2, ok := that.(Sidechain)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Operator != that1.Operator {
		return false
	}
	if len(this.SignerKeys) != len(that1.SignerKeys) {
		return false
	}
	for i := range this.SignerKeys {
		if !this.SignerKeys[i].Equal(that1.SignerKeys[i]) {
			return false
		}
	}
	if this.SignatureThreshold != that1.SignatureThreshold {
		return false
	}
	if this.SignerSetVersion != that1.SignerSetVersion {
		return false
	}
	if this.Tier != that1.Tier {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.Bond.Equal(&that1.Bond) {
		return false
	}
	if this.CheckpointIntervalSeconds != that1.CheckpointIntervalSeconds {
		return false
	}
	if this.LastCheckpointSequence != that1.LastCheckpointSequence {
		return false
	}
	if this.LastCheckpointHeight != that1.LastCheckpointHeight {
		return false
	}
	if !bytes.Equal(this.LastCheckpointHash, that1.LastCheckpointHash) {
		return false
	}
	if !this.RegisteredAt.Equal(that1.RegisteredAt) {
		return false
	}
	if that1.LastCheckpointAt == nil {
		if this.LastCheckpointAt != nil {
			return false
		}
	} else if !this.LastCheckpointAt.Equal(*that1.LastCheckpointAt) {
		return false
	}
	if that1.ExitRequestedAt == nil {
		if this.ExitRequestedAt != nil {
			return false
		}
	} else if !this.ExitRequestedAt.Equal(*that1.ExitRequestedAt) {
		return false
	}
	if that1.BondReturnAt == nil {
		if this.BondReturnAt != nil {
			return false
		}
	} else if !this.BondReturnAt.Equal(*that1.BondReturnAt) {
		return false
	}
	if this.MetadataUri != that1.MetadataUri {
		return false
	}
	return true
}
func (m *Sidechain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sidechain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sidechain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataUri) > 0 {
		i -= len(m.MetadataUri)
		copy(dAtA[i:], m.MetadataUri)
		i = encodeVarintSidechain(dAtA, i, uint64(len(m.MetadataUri)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.BondReturnAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.BondReturnAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BondReturnAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintSidechain(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.ExitRequestedAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ExitRequestedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExitRequestedAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintSidechain(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.LastCheckpointAt != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastCheckpointAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastCheckpointAt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintSidechain(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x7a
	}
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.RegisteredAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RegisteredAt):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintSidechain(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x72
	if len(m.LastCheckpointHash) > 0 {
		i -= len(m.LastCheckpointHash)
		copy(dAtA[i:], m.LastCheckpointHash)
		i = encodeVarintSidechain(dAtA, i, uint64(len(m.LastCheckpointHash)))
		i--
		dAtA[i] = 0x6a
	}
	if m.LastCheckpointHeight != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.LastCheckpointHeight))
		i--
		dAtA[i] = 0x60
	}
	if m.LastCheckpointSequence != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.LastCheckpointSequence))
		i--
		dAtA[i] = 0x58
	}
	if m.CheckpointIntervalSeconds != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.CheckpointIntervalSeconds))
		i--
		dAtA[i] = 0x50
	}
	{
		size, err := m.Bond.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSidechain(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.Status != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if m.Tier != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.Tier))
		i--
		dAtA[i] = 0x38
	}
	if m.SignerSetVersion != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.SignerSetVersion))
		i--
		dAtA[i] = 0x30
	}
	if m.SignatureThreshold != 0 {
		i = encodeVarintSidechain(dAtA, i, uint64(m.SignatureThreshold))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SignerKeys) > 0 {
		for iNdEx := len(m.SignerKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignerKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSidechain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintSidechain(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSidechain(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSidechain(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSidechain(dAtA []byte, offset int, v uint64) int {
	offset -= sovSidechain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sidechain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSidechain(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSidechain(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovSidechain(uint64(l))
	}
	if len(m.SignerKeys) > 0 {
		for _, e := range m.SignerKeys {
			l = e.Size()
			n += 1 + l + sovSidechain(uint64(l))
		}
	}
	if m.SignatureThreshold != 0 {
		n += 1 + sovSidechain(uint64(m.SignatureThreshold))
	}
	if m.SignerSetVersion != 0 {
		n += 1 + sovSidechain(uint64(m.SignerSetVersion))
	}
	if m.Tier != 0 {
		n += 1 + sovSidechain(uint64(m.Tier))
	}
	if m.Status != 0 {
		n += 1 + sovSidechain(uint64(m.Status))
	}
	l = m.Bond.Size()
	n += 1 + l + sovSidechain(uint64(l))
	if m.CheckpointIntervalSeconds != 0 {
		n += 1 + sovSidechain(uint64(m.CheckpointIntervalSeconds))
	}
	if m.LastCheckpointSequence != 0 {
		n += 1 + sovSidechain(uint64(m.LastCheckpointSequence))
	}
	if m.LastCheckpointHeight != 0 {
		n += 1 + sovSidechain(uint64(m.LastCheckpointHeight))
	}
	l = len(m.LastCheckpointHash)
	if l > 0 {
		n += 1 + l + sovSidechain(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RegisteredAt)
	n += 1 + l + sovSidechain(uint64(l))
	if m.LastCheckpointAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastCheckpointAt)
		n += 1 + l + sovSidechain(uint64(l))
	}
	if m.ExitRequestedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExitRequestedAt)
		n += 2 + l + sovSidechain(uint64(l))
	}
	if m.BondReturnAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BondReturnAt)
		n += 2 + l + sovSidechain(uint64(l))
	}
	l = len(m.MetadataUri)
	if l > 0 {
		n += 2 + l + sovSidechain(uint64(l))
	}
	return n
}

func sovSidechain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSidechain(x uint64) (n int) {
	return sovSidechain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sidechain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidechain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sidechain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sidechain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerKeys = append(m.SignerKeys, &any.Any{})
			if err := m.SignerKeys[len(m.SignerKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureThreshold", wireType)
			}
			m.SignatureThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignatureThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerSetVersion", wireType)
			}
			m.SignerSetVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerSetVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			m.Tier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tier |= AssuranceTier(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= SidechainStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointIntervalSeconds", wireType)
			}
			m.CheckpointIntervalSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckpointIntervalSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheckpointSequence", wireType)
			}
			m.LastCheckpointSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastCheckpointSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheckpointHeight", wireType)
			}
			m.LastCheckpointHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastCheckpointHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheckpointHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCheckpointHash = append(m.LastCheckpointHash[:0], dAtA[iNdEx:postIndex]...)
			if m.LastCheckpointHash == nil {
				m.LastCheckpointHash = []byte{}
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.RegisteredAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheckpointAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastCheckpointAt == nil {
				m.LastCheckpointAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastCheckpointAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitRequestedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExitRequestedAt == nil {
				m.ExitRequestedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ExitRequestedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondReturnAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BondReturnAt == nil {
				m.BondReturnAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.BondReturnAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidechain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidechain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSidechain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidechain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSidechain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSidechain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSidechain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSidechain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSidechain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSidechain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSidechain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSidechain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSidechain = fmt.Errorf("proto: unexpected end of group")
)
