// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lucidchain/proto/sidechain/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	any "github.com/cosmos/gogoproto/types/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterSidechain struct {
	Operator                  string        `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Id                        string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SignerKeys                []*any.Any    `protobuf:"bytes,4,rep,name=signer_keys,json=signerKeys,proto3" json:"signer_keys,omitempty"`
	SignatureThreshold        uint32        `protobuf:"varint,5,opt,name=signature_threshold,json=signatureThreshold,proto3" json:"signature_threshold,omitempty"`
	Tier                      AssuranceTier `protobuf:"varint,6,opt,name=tier,proto3,enum=lucidchain.proto.sidechain.v1.AssuranceTier" json:"tier,omitempty"`
	Bond                      types.Coin    `protobuf:"bytes,7,opt,name=bond,proto3" json:"bond"`
	CheckpointIntervalSeconds uint64        `protobuf:"varint,8,opt,name=checkpoint_interval_seconds,json=checkpointIntervalSeconds,proto3" json:"checkpoint_interval_seconds,omitempty"`
	MetadataUri               string        `protobuf:"bytes,9,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
}

func (m *MsgRegisterSidechain) Reset()         { *m = MsgRegisterSidechain{} }
func (m *MsgRegisterSidechain) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterSidechain) ProtoMessage()    {}
func (*MsgRegisterSidechain) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{0}
}
func (m *MsgRegisterSidechain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterSidechain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterSidechain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterSidechain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterSidechain.Merge(m, src)
}
func (m *MsgRegisterSidechain) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterSidechain) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterSidechain.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterSidechain proto.InternalMessageInfo

func (m *MsgRegisterSidechain) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgRegisterSidechain) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgRegisterSidechain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRegisterSidechain) GetSignerKeys() []*any.Any {
	if m != nil {
		return m.SignerKeys
	}
	return nil
}

func (m *MsgRegisterSidechain) GetSignatureThreshold() uint32 {
	if m != nil {
		return m.SignatureThreshold
	}
	return 0
}

func (m *MsgRegisterSidechain) GetTier() AssuranceTier {
	if m != nil {
		return m.Tier
	}
	return AssuranceTier_ASSURANCE_TIER_UNSPECIFIED
}

func (m *MsgRegisterSidechain) GetBond() types.Coin {
	if m != nil {
		return m.Bond
	}
	return types.Coin{}
}

func (m *MsgRegisterSidechain) GetCheckpointIntervalSeconds() uint64 {
	if m != nil {
		return m.CheckpointIntervalSeconds
	}
	return 0
}

func (m *MsgRegisterSidechain) GetMetadataUri() string {
	if m != nil {
		return m.MetadataUri
	}
	return ""
}

type MsgRegisterSidechainResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRegisterSidechainResponse) Reset()         { *m = MsgRegisterSidechainResponse{} }
func (m *MsgRegisterSidechainResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterSidechainResponse) ProtoMessage()    {}
func (*MsgRegisterSidechainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{1}
}
func (m *MsgRegisterSidechainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterSidechainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterSidechainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterSidechainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterSidechainResponse.Merge(m, src)
}
func (m *MsgRegisterSidechainResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterSidechainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterSidechainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterSidechainResponse proto.InternalMessageInfo

func (m *MsgRegisterSidechainResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgUpdateSigners struct {
	Operator           string     `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Id                 string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SignerKeys         []*any.Any `protobuf:"bytes,3,rep,name=signer_keys,json=signerKeys,proto3" json:"signer_keys,omitempty"`
	SignatureThreshold uint32     `protobuf:"varint,4,opt,name=signature_threshold,json=signatureThreshold,proto3" json:"signature_threshold,omitempty"`
}

func (m *MsgUpdateSigners) Reset()         { *m = MsgUpdateSigners{} }
func (m *MsgUpdateSigners) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSigners) ProtoMessage()    {}
func (*MsgUpdateSigners) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{2}
}
func (m *MsgUpdateSigners) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSigners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSigners.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSigners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSigners.Merge(m, src)
}
func (m *MsgUpdateSigners) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSigners) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSigners.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSigners proto.InternalMessageInfo

func (m *MsgUpdateSigners) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgUpdateSigners) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgUpdateSigners) GetSignerKeys() []*any.Any {
	if m != nil {
		return m.SignerKeys
	}
	return nil
}

func (m *MsgUpdateSigners) GetSignatureThreshold() uint32 {
	if m != nil {
		return m.SignatureThreshold
	}
	return 0
}

type MsgUpdateSignersResponse struct {
	// The new Sidechain.signer_set_version.
	SignerSetVersion uint64 `protobuf:"varint,1,opt,name=signer_set_version,json=signerSetVersion,proto3" json:"signer_set_version,omitempty"`
}

func (m *MsgUpdateSignersResponse) Reset()         { *m = MsgUpdateSignersResponse{} }
func (m *MsgUpdateSignersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSignersResponse) ProtoMessage()    {}
func (*MsgUpdateSignersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{3}
}
func (m *MsgUpdateSignersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSignersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSignersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSignersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSignersResponse.Merge(m, src)
}
func (m *MsgUpdateSignersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSignersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSignersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSignersResponse proto.InternalMessageInfo

func (m *MsgUpdateSignersResponse) GetSignerSetVersion() uint64 {
	if m != nil {
		return m.SignerSetVersion
	}
	return 0
}

type MsgRequestTierUpgrade struct {
	Operator       string        `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Id             string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RequestedTier  AssuranceTier `protobuf:"varint,3,opt,name=requested_tier,json=requestedTier,proto3,enum=lucidchain.proto.sidechain.v1.AssuranceTier" json:"requested_tier,omitempty"`
	AdditionalBond types.Coin    `protobuf:"bytes,4,opt,name=additional_bond,json=additionalBond,proto3" json:"additional_bond"`
}

func (m *MsgRequestTierUpgrade) Reset()         { *m = MsgRequestTierUpgrade{} }
func (m *MsgRequestTierUpgrade) String() string { return proto.CompactTextString(m) }
func (*MsgRequestTierUpgrade) ProtoMessage()    {}
func (*MsgRequestTierUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{4}
}
func (m *MsgRequestTierUpgrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestTierUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestTierUpgrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestTierUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestTierUpgrade.Merge(m, src)
}
func (m *MsgRequestTierUpgrade) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestTierUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestTierUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestTierUpgrade proto.InternalMessageInfo

func (m *MsgRequestTierUpgrade) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgRequestTierUpgrade) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgRequestTierUpgrade) GetRequestedTier() AssuranceTier {
	if m != nil {
		return m.RequestedTier
	}
	return AssuranceTier_ASSURANCE_TIER_UNSPECIFIED
}

func (m *MsgRequestTierUpgrade) GetAdditionalBond() types.Coin {
	if m != nil {
		return m.AdditionalBond
	}
	return types.Coin{}
}

type MsgRequestTierUpgradeResponse struct {
}

func (m *MsgRequestTierUpgradeResponse) Reset()         { *m = MsgRequestTierUpgradeResponse{} }
func (m *MsgRequestTierUpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestTierUpgradeResponse) ProtoMessage()    {}
func (*MsgRequestTierUpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{5}
}
func (m *MsgRequestTierUpgradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestTierUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestTierUpgradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestTierUpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestTierUpgradeResponse.Merge(m, src)
}
func (m *MsgRequestTierUpgradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestTierUpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestTierUpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestTierUpgradeResponse proto.InternalMessageInfo

type MsgInitiateExit struct {
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgInitiateExit) Reset()         { *m = MsgInitiateExit{} }
func (m *MsgInitiateExit) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateExit) ProtoMessage()    {}
func (*MsgInitiateExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{6}
}
func (m *MsgInitiateExit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateExit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateExit.Merge(m, src)
}
func (m *MsgInitiateExit) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateExit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateExit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateExit proto.InternalMessageInfo

func (m *MsgInitiateExit) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgInitiateExit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgInitiateExitResponse struct {
	BondReturnAt time.Time `protobuf:"bytes,1,opt,name=bond_return_at,json=bondReturnAt,proto3,stdtime" json:"bond_return_at"`
}

func (m *MsgInitiateExitResponse) Reset()         { *m = MsgInitiateExitResponse{} }
func (m *MsgInitiateExitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateExitResponse) ProtoMessage()    {}
func (*MsgInitiateExitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{7}
}
func (m *MsgInitiateExitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateExitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateExitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateExitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateExitResponse.Merge(m, src)
}
func (m *MsgInitiateExitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateExitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateExitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateExitResponse proto.InternalMessageInfo

func (m *MsgInitiateExitResponse) GetBondReturnAt() time.Time {
	if m != nil {
		return m.BondReturnAt
	}
	return time.Time{}
}

type MsgUpdateParams struct {
	// Authority is the governance module account by default.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{8}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_295f9b124882b718, []int{9}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterSidechain)(nil), "lucidchain.proto.sidechain.v1.MsgRegisterSidechain")
	proto.RegisterType((*MsgRegisterSidechainResponse)(nil), "lucidchain.proto.sidechain.v1.MsgRegisterSidechainResponse")
	proto.RegisterType((*MsgUpdateSigners)(nil), "lucidchain.proto.sidechain.v1.MsgUpdateSigners")
	proto.RegisterType((*MsgUpdateSignersResponse)(nil), "lucidchain.proto.sidechain.v1.MsgUpdateSignersResponse")
	proto.RegisterType((*MsgRequestTierUpgrade)(nil), "lucidchain.proto.sidechain.v1.MsgRequestTierUpgrade")
	proto.RegisterType((*MsgRequestTierUpgradeResponse)(nil), "lucidchain.proto.sidechain.v1.MsgRequestTierUpgradeResponse")
	proto.RegisterType((*MsgInitiateExit)(nil), "lucidchain.proto.sidechain.v1.MsgInitiateExit")
	proto.RegisterType((*MsgInitiateExitResponse)(nil), "lucidchain.proto.sidechain.v1.MsgInitiateExitResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "lucidchain.proto.sidechain.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "lucidchain.proto.sidechain.v1.MsgUpdateParamsResponse")
}

func init() {
	proto.RegisterFile("lucidchain/proto/sidechain/v1/tx.proto", fileDescriptor_295f9b124882b718)
}

var fileDescriptor_295f9b124882b718 = []byte{
	// 912 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xc6, 0x6e, 0x49, 0xc6, 0x89, 0x53, 0x86, 0xa0, 0xac, 0x17, 0xea, 0x18, 0x4b, 0x20,
	0x0b, 0xb5, 0xbb, 0xc4, 0x41, 0x41, 0x2a, 0x08, 0x11, 0x57, 0x48, 0xfd, 0xa3, 0x88, 0x6a, 0x9d,
	0x70, 0xe0, 0xb2, 0x1a, 0xef, 0xbe, 0xae, 0x47, 0xb5, 0x67, 0x96, 0x99, 0x59, 0x2b, 0x7b, 0x05,
	0x21, 0x21, 0x71, 0xe9, 0x27, 0xe0, 0x33, 0x70, 0xe0, 0x0b, 0x70, 0xab, 0x38, 0x55, 0x9c, 0x38,
	0x01, 0x4a, 0x0e, 0x88, 0x6f, 0x81, 0x76, 0xf6, 0x8f, 0x13, 0x27, 0xc4, 0x49, 0x54, 0x6e, 0x7e,
	0xef, 0xfd, 0xde, 0xbf, 0xdf, 0xef, 0xed, 0xc8, 0xe8, 0xbd, 0x51, 0xec, 0xd3, 0xc0, 0x1f, 0x12,
	0xca, 0x9c, 0x48, 0x70, 0xc5, 0x1d, 0x49, 0x03, 0xc8, 0xec, 0xc9, 0x96, 0xa3, 0x0e, 0x6d, 0xed,
	0xc5, 0xb7, 0xa7, 0xb8, 0xcc, 0x63, 0x97, 0x38, 0x7b, 0xb2, 0x65, 0xad, 0x87, 0x3c, 0xe4, 0x59,
	0x7e, 0xfa, 0x2b, 0x83, 0x58, 0x0d, 0x9f, 0xcb, 0x31, 0x97, 0x5e, 0x16, 0xc8, 0x8c, 0x3c, 0xb4,
	0x91, 0x59, 0xce, 0x58, 0x86, 0x69, 0x9f, 0xb1, 0x0c, 0xf3, 0x40, 0x33, 0x0f, 0x0c, 0x88, 0x04,
	0x67, 0xb2, 0x35, 0x00, 0x45, 0xb6, 0x1c, 0x9f, 0x17, 0x6d, 0xad, 0x46, 0xc8, 0x79, 0x38, 0x82,
	0x6c, 0xd8, 0x41, 0xfc, 0xd4, 0x21, 0x2c, 0xc9, 0x43, 0x9b, 0xb3, 0x21, 0x45, 0xc7, 0x20, 0x15,
	0x19, 0x47, 0x39, 0xe0, 0xee, 0xc5, 0xcb, 0x4e, 0x37, 0xd2, 0xc1, 0xf6, 0x2f, 0x15, 0xb4, 0xbe,
	0x27, 0x43, 0x17, 0x42, 0x2a, 0x15, 0x88, 0x7e, 0x11, 0xc6, 0x16, 0x5a, 0xe2, 0x11, 0x08, 0xa2,
	0xb8, 0x30, 0x8d, 0x96, 0xd1, 0x59, 0x76, 0x4b, 0x1b, 0xd7, 0xd1, 0x22, 0x0d, 0xcc, 0x45, 0xed,
	0x5d, 0xa4, 0x01, 0xc6, 0xa8, 0xca, 0xc8, 0x18, 0xcc, 0x8a, 0xf6, 0xe8, 0xdf, 0xf8, 0x0b, 0x54,
	0x93, 0x34, 0x64, 0x20, 0xbc, 0x67, 0x90, 0x48, 0xb3, 0xda, 0xaa, 0x74, 0x6a, 0xdd, 0x75, 0x3b,
	0x1b, 0xdf, 0x2e, 0xc6, 0xb7, 0x77, 0x59, 0xd2, 0x33, 0x7f, 0xfd, 0xf9, 0xee, 0x7a, 0xce, 0x9c,
	0x2f, 0x92, 0x48, 0x71, 0xfb, 0x49, 0x3c, 0x78, 0x0c, 0x89, 0x8b, 0xb2, 0x12, 0x8f, 0x21, 0x91,
	0xd8, 0x41, 0x6f, 0xa4, 0x16, 0x51, 0xb1, 0x00, 0x4f, 0x0d, 0x05, 0xc8, 0x21, 0x1f, 0x05, 0xe6,
	0x8d, 0x96, 0xd1, 0x59, 0x75, 0x71, 0x19, 0xda, 0x2f, 0x22, 0xf8, 0x33, 0x54, 0x55, 0x14, 0x84,
	0x79, 0xb3, 0x65, 0x74, 0xea, 0xdd, 0x3b, 0xf6, 0x85, 0xea, 0xda, 0xbb, 0x52, 0xc6, 0x82, 0x30,
	0x1f, 0xf6, 0x29, 0x08, 0x57, 0x67, 0xe2, 0x6d, 0x54, 0x1d, 0x70, 0x16, 0x98, 0xaf, 0xb5, 0x8c,
	0x4e, 0xad, 0xdb, 0xb0, 0xf3, 0x19, 0x53, 0xd9, 0xec, 0x5c, 0x36, 0xfb, 0x3e, 0xa7, 0xac, 0x57,
	0x7d, 0xf1, 0xc7, 0xe6, 0x82, 0xab, 0xc1, 0xf8, 0x53, 0xf4, 0x96, 0x3f, 0x04, 0xff, 0x59, 0xc4,
	0x29, 0x53, 0x1e, 0x65, 0x0a, 0xc4, 0x84, 0x8c, 0x3c, 0x09, 0x3e, 0x67, 0x81, 0x34, 0x97, 0x5a,
	0x46, 0xa7, 0xea, 0x36, 0xa6, 0x90, 0x87, 0x39, 0xa2, 0x9f, 0x01, 0xf0, 0x3b, 0x68, 0x65, 0x0c,
	0x8a, 0x04, 0x44, 0x11, 0x2f, 0x16, 0xd4, 0x5c, 0xd6, 0xa4, 0xd6, 0x0a, 0xdf, 0x81, 0xa0, 0xf7,
	0x56, 0xbf, 0xf9, 0xfb, 0xa7, 0xf7, 0x4b, 0x39, 0xda, 0x36, 0x7a, 0xfb, 0x3c, 0x09, 0x5d, 0x90,
	0x11, 0x67, 0x12, 0x72, 0xb9, 0x8c, 0x42, 0xae, 0xf6, 0x3f, 0x06, 0xba, 0xb5, 0x27, 0xc3, 0x83,
	0x28, 0x20, 0x0a, 0xfa, 0x9a, 0x61, 0x89, 0x3f, 0x9c, 0xd5, 0xbb, 0x67, 0xfe, 0x36, 0x95, 0x65,
	0x37, 0x08, 0x04, 0x48, 0xd9, 0x57, 0x82, 0xb2, 0xf0, 0x82, 0x4b, 0x98, 0x51, 0xbd, 0xf2, 0x7f,
	0xa9, 0x5e, 0xfd, 0x2f, 0xd5, 0x67, 0xb9, 0x79, 0x80, 0xcc, 0xd9, 0x55, 0x4b, 0x5e, 0xee, 0x20,
	0x9c, 0x0f, 0x2b, 0x41, 0x79, 0x13, 0x10, 0x92, 0x72, 0xa6, 0x97, 0xaf, 0xba, 0xb7, 0xb2, 0x48,
	0x1f, 0xd4, 0x97, 0x99, 0xbf, 0xfd, 0xc3, 0x22, 0x7a, 0x53, 0xd3, 0xfc, 0x75, 0x0c, 0x52, 0xa5,
	0x57, 0x72, 0x10, 0x85, 0x82, 0x04, 0xf0, 0x8a, 0xa8, 0xeb, 0xa3, 0xba, 0xc8, 0x6a, 0x43, 0xe0,
	0xe9, 0xc3, 0xad, 0x5c, 0xe3, 0x70, 0x57, 0xcb, 0x1a, 0xa9, 0x89, 0x1f, 0xa0, 0x35, 0x12, 0x04,
	0x54, 0x51, 0xce, 0xc8, 0xc8, 0xd3, 0xc7, 0x5c, 0xbd, 0xdc, 0x31, 0xd7, 0xa7, 0x79, 0x3d, 0xce,
	0xce, 0xf0, 0xba, 0x89, 0x6e, 0x9f, 0x4b, 0x46, 0x41, 0x6e, 0xfb, 0x29, 0x5a, 0xdb, 0x93, 0xe1,
	0x43, 0x46, 0x15, 0x25, 0x0a, 0x3e, 0x3f, 0xa4, 0xea, 0xd5, 0xf0, 0x34, 0x3b, 0x08, 0xa0, 0x8d,
	0x99, 0x3e, 0xa5, 0xbe, 0x8f, 0x50, 0x3d, 0xdd, 0xd8, 0x13, 0xa0, 0x62, 0xc1, 0x3c, 0xa2, 0x74,
	0xd7, 0x5a, 0xd7, 0x3a, 0x73, 0x8f, 0xfb, 0xc5, 0x23, 0xda, 0x5b, 0x4a, 0x97, 0x7f, 0xfe, 0xe7,
	0xa6, 0xe1, 0xae, 0xa4, 0xb9, 0xae, 0x4e, 0xdd, 0x55, 0xed, 0x1f, 0x0d, 0xb4, 0x56, 0x1e, 0xd2,
	0x13, 0x22, 0xc8, 0x58, 0xe2, 0x1d, 0xb4, 0x4c, 0x62, 0x35, 0xe4, 0x82, 0xaa, 0x64, 0xee, 0x42,
	0x53, 0x28, 0xbe, 0x8f, 0x6e, 0x46, 0xba, 0x82, 0xde, 0xaa, 0xd6, 0x7d, 0x77, 0x8e, 0xc2, 0x59,
	0xbb, 0x5c, 0x97, 0x3c, 0xf5, 0x5e, 0x3d, 0xa5, 0x61, 0x5a, 0xb4, 0xdd, 0x40, 0x1b, 0x33, 0xf3,
	0x15, 0x3c, 0x74, 0xbf, 0xbd, 0x81, 0x2a, 0x7b, 0x32, 0xc4, 0xdf, 0x19, 0xe8, 0xf5, 0xb3, 0x0f,
	0xfd, 0xf6, 0x9c, 0xee, 0xe7, 0x3d, 0x2d, 0xd6, 0xc7, 0xd7, 0x48, 0x2a, 0x75, 0x49, 0xd0, 0xea,
	0xe9, 0xb7, 0xc7, 0x99, 0x5f, 0xed, 0x54, 0x82, 0xf5, 0xd1, 0x15, 0x13, 0xca, 0xd6, 0xdf, 0x1b,
	0x08, 0x9f, 0xf7, 0x05, 0x5f, 0x66, 0x9d, 0xd9, 0x2c, 0xeb, 0x93, 0xeb, 0x64, 0x95, 0xa3, 0x4c,
	0xd0, 0xca, 0xa9, 0xaf, 0xc3, 0x9e, 0x5f, 0xed, 0x24, 0xde, 0xda, 0xb9, 0x1a, 0xfe, 0x64, 0xdf,
	0x53, 0x57, 0x6c, 0x5f, 0x96, 0xcb, 0x0c, 0x6f, 0xed, 0x5c, 0x0d, 0x5f, 0xf4, 0xed, 0x3d, 0x7a,
	0x71, 0xd4, 0x34, 0x5e, 0x1e, 0x35, 0x8d, 0xbf, 0x8e, 0x9a, 0xc6, 0xf3, 0xe3, 0xe6, 0xc2, 0xcb,
	0xe3, 0xe6, 0xc2, 0xef, 0xc7, 0xcd, 0x85, 0xaf, 0x3e, 0x08, 0xa9, 0x1a, 0xc6, 0x03, 0xdb, 0xe7,
	0x63, 0x47, 0xd7, 0x8e, 0x48, 0xe2, 0x4c, 0x9b, 0x38, 0x87, 0x27, 0xfe, 0xc2, 0xa8, 0x24, 0x02,
	0x39, 0xb8, 0xa9, 0xfb, 0x6e, 0xff, 0x3b, 0x00, 0x31, 0x69, 0xc2, 0x68, 0xda, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterSidechain registers a new sidechain and posts its bond.
	RegisterSidechain(ctx context.Context, in *MsgRegisterSidechain, opts ...grpc.CallOption) (*MsgRegisterSidechainResponse, error)
	// UpdateSigners rotates the set of authorized checkpoint signer keys.
	UpdateSigners(ctx context.Context, in *MsgUpdateSigners, opts ...grpc.CallOption) (*MsgUpdateSignersResponse, error)
	// RequestTierUpgrade requests a move to a higher assurance tier (e.g. Notarized -> Attested).
	// Subject to additional bond and, for Tier 2+, attestor availability.
	RequestTierUpgrade(ctx context.Context, in *MsgRequestTierUpgrade, opts ...grpc.CallOption) (*MsgRequestTierUpgradeResponse, error)
	// InitiateExit begins voluntary deregistration; bond is returned after the cooldown.
	InitiateExit(ctx context.Context, in *MsgInitiateExit, opts ...grpc.CallOption) (*MsgInitiateExitResponse, error)
	// UpdateParams updates module parameters via governance.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterSidechain(ctx context.Context, in *MsgRegisterSidechain, opts ...grpc.CallOption) (*MsgRegisterSidechainResponse, error) {
	out := new(MsgRegisterSidechainResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.proto.sidechain.v1.Msg/RegisterSidechain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSigners(ctx context.Context, in *MsgUpdateSigners, opts ...grpc.CallOption) (*MsgUpdateSignersResponse, error) {
	out := new(MsgUpdateSignersResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.proto.sidechain.v1.Msg/UpdateSigners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestTierUpgrade(ctx context.Context, in *MsgRequestTierUpgrade, opts ...grpc.CallOption) (*MsgRequestTierUpgradeResponse, error) {
	out := new(MsgRequestTierUpgradeResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.proto.sidechain.v1.Msg/RequestTierUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitiateExit(ctx context.Context, in *MsgInitiateExit, opts ...grpc.CallOption) (*MsgInitiateExitResponse, error) {
	out := new(MsgInitiateExitResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.proto.sidechain.v1.Msg/InitiateExit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/lucidchain.proto.sidechain.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterSidechain registers a new sidechain and posts its bond.
	RegisterSidechain(context.Context, *MsgRegisterSidechain) (*MsgRegisterSidechainResponse, error)
	// UpdateSigners rotates the set of authorized checkpoint signer keys.
	UpdateSigners(context.Context, *MsgUpdateSigners) (*MsgUpdateSignersResponse, error)
	// RequestTierUpgrade requests a move to a higher assurance tier (e.g. Notarized -> Attested).
	// Subject to additional bond and, for Tier 2+, attestor availability.
	RequestTierUpgrade(context.Context, *MsgRequestTierUpgrade) (*MsgRequestTierUpgradeResponse, error)
	// InitiateExit begins voluntary deregistration; bond is returned after the cooldown.
	InitiateExit(context.Context, *MsgInitiateExit) (*MsgInitiateExitResponse, error)
	// UpdateParams updates module parameters via governance.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterSidechain(ctx context.Context, req *MsgRegisterSidechain) (*MsgRegisterSidechainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSidechain not implemented")
}
func (*UnimplementedMsgServer) UpdateSigners(ctx context.Context, req *MsgUpdateSigners) (*MsgUpdateSignersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSigners not implemented")
}
func (*UnimplementedMsgServer) RequestTierUpgrade(ctx context.Context, req *MsgRequestTierUpgrade) (*MsgRequestTierUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTierUpgrade not implemented")
}
func (*UnimplementedMsgServer) InitiateExit(ctx context.Context, req *MsgInitiateExit) (*MsgInitiateExitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateExit not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterSidechain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterSidechain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterSidechain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.proto.sidechain.v1.Msg/RegisterSidechain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterSidechain(ctx, req.(*MsgRegisterSidechain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSigners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSigners)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSigners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.proto.sidechain.v1.Msg/UpdateSigners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSigners(ctx, req.(*MsgUpdateSigners))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestTierUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestTierUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestTierUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.proto.sidechain.v1.Msg/RequestTierUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestTierUpgrade(ctx, req.(*MsgRequestTierUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitiateExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiateExit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitiateExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.proto.sidechain.v1.Msg/InitiateExit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitiateExit(ctx, req.(*MsgInitiateExit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lucidchain.proto.sidechain.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lucidchain.proto.sidechain.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSidechain",
			Handler:    _Msg_RegisterSidechain_Handler,
		},
		{
			MethodName: "UpdateSigners",
			Handler:    _Msg_UpdateSigners_Handler,
		},
		{
			MethodName: "RequestTierUpgrade",
			Handler:    _Msg_RequestTierUpgrade_Handler,
		},
		{
			MethodName: "InitiateExit",
			Handler:    _Msg_InitiateExit_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lucidchain/proto/sidechain/v1/tx.proto",
}

func (m *MsgRegisterSidechain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterSidechain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterSidechain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataUri) > 0 {
		i -= len(m.MetadataUri)
		copy(dAtA[i:], m.MetadataUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MetadataUri)))
		i--
		dAtA[i] = 0x4a
	}
	if m.CheckpointIntervalSeconds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CheckpointIntervalSeconds))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.Bond.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.Tier != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Tier))
		i--
		dAtA[i] = 0x30
	}
	if m.SignatureThreshold != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignatureThreshold))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SignerKeys) > 0 {
		for iNdEx := len(m.SignerKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignerKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterSidechainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterSidechainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterSidechainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSigners) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSigners) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSigners) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignatureThreshold != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignatureThreshold))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SignerKeys) > 0 {
		for iNdEx := len(m.SignerKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignerKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSignersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSignersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSignersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignerSetVersion != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignerSetVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestTierUpgrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestTierUpgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestTierUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AdditionalBond.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.RequestedTier != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestedTier))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestTierUpgradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestTierUpgradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestTierUpgradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInitiateExit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateExit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateExit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitiateExitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateExitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateExitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.BondReturnAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.BondReturnAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTx(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterSidechain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.SignerKeys) > 0 {
		for _, e := range m.SignerKeys {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.SignatureThreshold != 0 {
		n += 1 + sovTx(uint64(m.SignatureThreshold))
	}
	if m.Tier != 0 {
		n += 1 + sovTx(uint64(m.Tier))
	}
	l = m.Bond.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.CheckpointIntervalSeconds != 0 {
		n += 1 + sovTx(uint64(m.CheckpointIntervalSeconds))
	}
	l = len(m.MetadataUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterSidechainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateSigners) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.SignerKeys) > 0 {
		for _, e := range m.SignerKeys {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.SignatureThreshold != 0 {
		n += 1 + sovTx(uint64(m.SignatureThreshold))
	}
	return n
}

func (m *MsgUpdateSignersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SignerSetVersion != 0 {
		n += 1 + sovTx(uint64(m.SignerSetVersion))
	}
	return n
}

func (m *MsgRequestTierUpgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RequestedTier != 0 {
		n += 1 + sovTx(uint64(m.RequestedTier))
	}
	l = m.AdditionalBond.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRequestTierUpgradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInitiateExit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitiateExitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.BondReturnAt)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterSidechain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterSidechain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterSidechain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerKeys = append(m.SignerKeys, &any.Any{})
			if err := m.SignerKeys[len(m.SignerKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureThreshold", wireType)
			}
			m.SignatureThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignatureThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			m.Tier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tier |= AssuranceTier(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointIntervalSeconds", wireType)
			}
			m.CheckpointIntervalSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckpointIntervalSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterSidechainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterSidechainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterSidechainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSigners) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSigners: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSigners: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerKeys = append(m.SignerKeys, &any.Any{})
			if err := m.SignerKeys[len(m.SignerKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureThreshold", wireType)
			}
			m.SignatureThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignatureThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSignersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSignersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSignersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerSetVersion", wireType)
			}
			m.SignerSetVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerSetVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestTierUpgrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestTierUpgrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestTierUpgrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedTier", wireType)
			}
			m.RequestedTier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedTier |= AssuranceTier(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdditionalBond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AdditionalBond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestTierUpgradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestTierUpgradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestTierUpgradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitiateExit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateExit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateExit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitiateExitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateExitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateExitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondReturnAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.BondReturnAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
