// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lucidchain/attestor/v1/attestor.proto

package types

import (
	bytes "bytes"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AttestorStatus defines the lifecycle state of a registered attestor.
type AttestorStatus int32

const (
	AttestorStatus_ATTESTOR_STATUS_UNSPECIFIED AttestorStatus = 0
	AttestorStatus_ATTESTOR_STATUS_PENDING     AttestorStatus = 1
	AttestorStatus_ATTESTOR_STATUS_ACTIVE      AttestorStatus = 2
	AttestorStatus_ATTESTOR_STATUS_SUSPENDED   AttestorStatus = 3
	AttestorStatus_ATTESTOR_STATUS_SLASHED     AttestorStatus = 4
	AttestorStatus_ATTESTOR_STATUS_EXITED      AttestorStatus = 5
)

var AttestorStatus_name = map[int32]string{
	0: "ATTESTOR_STATUS_UNSPECIFIED",
	1: "ATTESTOR_STATUS_PENDING",
	2: "ATTESTOR_STATUS_ACTIVE",
	3: "ATTESTOR_STATUS_SUSPENDED",
	4: "ATTESTOR_STATUS_SLASHED",
	5: "ATTESTOR_STATUS_EXITED",
}

var AttestorStatus_value = map[string]int32{
	"ATTESTOR_STATUS_UNSPECIFIED": 0,
	"ATTESTOR_STATUS_PENDING":     1,
	"ATTESTOR_STATUS_ACTIVE":      2,
	"ATTESTOR_STATUS_SUSPENDED":   3,
	"ATTESTOR_STATUS_SLASHED":     4,
	"ATTESTOR_STATUS_EXITED":      5,
}

func (x AttestorStatus) String() string {
	return proto.EnumName(AttestorStatus_name, int32(x))
}

func (AttestorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{0}
}

// AttestationStatus tracks the dispute lifecycle of a single attestation.
type AttestationStatus int32

const (
	AttestationStatus_ATTESTATION_STATUS_UNSPECIFIED AttestationStatus = 0
	AttestationStatus_ATTESTATION_STATUS_ACTIVE      AttestationStatus = 1
	AttestationStatus_ATTESTATION_STATUS_DISPUTED    AttestationStatus = 2
	AttestationStatus_ATTESTATION_STATUS_UPHELD      AttestationStatus = 3
	AttestationStatus_ATTESTATION_STATUS_OVERTURNED  AttestationStatus = 4
	AttestationStatus_ATTESTATION_STATUS_REVOKED     AttestationStatus = 5
)

var AttestationStatus_name = map[int32]string{
	0: "ATTESTATION_STATUS_UNSPECIFIED",
	1: "ATTESTATION_STATUS_ACTIVE",
	2: "ATTESTATION_STATUS_DISPUTED",
	3: "ATTESTATION_STATUS_UPHELD",
	4: "ATTESTATION_STATUS_OVERTURNED",
	5: "ATTESTATION_STATUS_REVOKED",
}

var AttestationStatus_value = map[string]int32{
	"ATTESTATION_STATUS_UNSPECIFIED": 0,
	"ATTESTATION_STATUS_ACTIVE":      1,
	"ATTESTATION_STATUS_DISPUTED":    2,
	"ATTESTATION_STATUS_UPHELD":      3,
	"ATTESTATION_STATUS_OVERTURNED":  4,
	"ATTESTATION_STATUS_REVOKED":     5,
}

func (x AttestationStatus) String() string {
	return proto.EnumName(AttestationStatus_name, int32(x))
}

func (AttestationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{1}
}

// Attestor is the on-chain registration record for a qualified attesting entity
// (e.g. a certification body, auditor, or regulator).
type Attestor struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Operator string `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	// Domains this attestor is qualified to attest in, referencing published
	// AttestationSchema ids (e.g. "hospitality.revenue-report.v1").
	AuthorizedSchemaIds []string              `protobuf:"bytes,4,rep,name=authorized_schema_ids,json=authorizedSchemaIds,proto3" json:"authorized_schema_ids,omitempty"`
	SignerPubkeys       []string              `protobuf:"bytes,5,rep,name=signer_pubkeys,json=signerPubkeys,proto3" json:"signer_pubkeys,omitempty"`
	SignatureThreshold  uint32                `protobuf:"varint,6,opt,name=signature_threshold,json=signatureThreshold,proto3" json:"signature_threshold,omitempty"`
	Status              AttestorStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=lucidchain.attestor.v1.AttestorStatus" json:"status,omitempty"`
	BondAmount          cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=bond_amount,json=bondAmount,proto3,customtype=cosmossdk.io/math.Int" json:"bond_amount"`
	// Simple reputation counter: successful attestations minus overturned ones.
	// Informational only -- not consensus-critical, not used in signature checks.
	ReputationScore int64     `protobuf:"varint,9,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	RegisteredAt    time.Time `protobuf:"bytes,10,opt,name=registered_at,json=registeredAt,proto3,stdtime" json:"registered_at"`
	// URI to off-chain credentials/accreditation evidence for this attestor.
	CredentialUri string `protobuf:"bytes,11,opt,name=credential_uri,json=credentialUri,proto3" json:"credential_uri,omitempty"`
}

func (m *Attestor) Reset()         { *m = Attestor{} }
func (m *Attestor) String() string { return proto.CompactTextString(m) }
func (*Attestor) ProtoMessage()    {}
func (*Attestor) Descriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{0}
}
func (m *Attestor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attestor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attestor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attestor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestor.Merge(m, src)
}
func (m *Attestor) XXX_Size() int {
	return m.Size()
}
func (m *Attestor) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestor.DiscardUnknown(m)
}

var xxx_messageInfo_Attestor proto.InternalMessageInfo

func (m *Attestor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attestor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attestor) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Attestor) GetAuthorizedSchemaIds() []string {
	if m != nil {
		return m.AuthorizedSchemaIds
	}
	return nil
}

func (m *Attestor) GetSignerPubkeys() []string {
	if m != nil {
		return m.SignerPubkeys
	}
	return nil
}

func (m *Attestor) GetSignatureThreshold() uint32 {
	if m != nil {
		return m.SignatureThreshold
	}
	return 0
}

func (m *Attestor) GetStatus() AttestorStatus {
	if m != nil {
		return m.Status
	}
	return AttestorStatus_ATTESTOR_STATUS_UNSPECIFIED
}

func (m *Attestor) GetReputationScore() int64 {
	if m != nil {
		return m.ReputationScore
	}
	return 0
}

func (m *Attestor) GetRegisteredAt() time.Time {
	if m != nil {
		return m.RegisteredAt
	}
	return time.Time{}
}

func (m *Attestor) GetCredentialUri() string {
	if m != nil {
		return m.CredentialUri
	}
	return ""
}

// AttestationSchema defines the shape and scope of a claim attestors can make.
// Published via governance so the exact wording of a claim -- and what it
// deliberately does NOT cover -- is fixed and auditable, not ad hoc per attestation.
type AttestationSchema struct {
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// Precise, narrow description of what a valid attestation under this schema asserts.
	ClaimDescription string `protobuf:"bytes,4,opt,name=claim_description,json=claimDescription,proto3" json:"claim_description,omitempty"`
	// Explicit statement of what is NOT covered (e.g. "does not verify underlying
	// transaction authenticity, only that reported figures match submitted source data").
	Exclusions string `protobuf:"bytes,5,opt,name=exclusions,proto3" json:"exclusions,omitempty"`
	// Data sources an attestor must consult per this schema (informational/off-chain process,
	// documented here for auditability).
	RequiredDataSources []string `protobuf:"bytes,6,rep,name=required_data_sources,json=requiredDataSources,proto3" json:"required_data_sources,omitempty"`
	// How long an attestation under this schema remains valid before it must be renewed.
	ValidityPeriodSeconds uint64 `protobuf:"varint,7,opt,name=validity_period_seconds,json=validityPeriodSeconds,proto3" json:"validity_period_seconds,omitempty"`
	// Dispute window during which an ATTESTATION_STATUS_ACTIVE attestation can be challenged.
	DisputeWindowSeconds uint64 `protobuf:"varint,8,opt,name=dispute_window_seconds,json=disputeWindowSeconds,proto3" json:"dispute_window_seconds,omitempty"`
	Active               bool   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *AttestationSchema) Reset()         { *m = AttestationSchema{} }
func (m *AttestationSchema) String() string { return proto.CompactTextString(m) }
func (*AttestationSchema) ProtoMessage()    {}
func (*AttestationSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{1}
}
func (m *AttestationSchema) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttestationSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttestationSchema.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttestationSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationSchema.Merge(m, src)
}
func (m *AttestationSchema) XXX_Size() int {
	return m.Size()
}
func (m *AttestationSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationSchema.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationSchema proto.InternalMessageInfo

func (m *AttestationSchema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttestationSchema) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AttestationSchema) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AttestationSchema) GetClaimDescription() string {
	if m != nil {
		return m.ClaimDescription
	}
	return ""
}

func (m *AttestationSchema) GetExclusions() string {
	if m != nil {
		return m.Exclusions
	}
	return ""
}

func (m *AttestationSchema) GetRequiredDataSources() []string {
	if m != nil {
		return m.RequiredDataSources
	}
	return nil
}

func (m *AttestationSchema) GetValidityPeriodSeconds() uint64 {
	if m != nil {
		return m.ValidityPeriodSeconds
	}
	return 0
}

func (m *AttestationSchema) GetDisputeWindowSeconds() uint64 {
	if m != nil {
		return m.DisputeWindowSeconds
	}
	return 0
}

func (m *AttestationSchema) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// Attestation is a signed claim by a registered attestor about a specific
// sidechain checkpoint (or, more generally, a specific on-chain reference).
type Attestation struct {
	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaId           string `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	AttestorId         string `protobuf:"bytes,3,opt,name=attestor_id,json=attestorId,proto3" json:"attestor_id,omitempty"`
	SidechainId        string `protobuf:"bytes,4,opt,name=sidechain_id,json=sidechainId,proto3" json:"sidechain_id,omitempty"`
	CheckpointSequence uint64 `protobuf:"varint,5,opt,name=checkpoint_sequence,json=checkpointSequence,proto3" json:"checkpoint_sequence,omitempty"`
	// Structured claim payload (schema-specific fields), encoded as JSON per the
	// schema's documented format. Kept off the hot path of consensus-critical logic --
	// the module treats this as an opaque, size-limited blob.
	ClaimPayload []byte            `protobuf:"bytes,6,opt,name=claim_payload,json=claimPayload,proto3" json:"claim_payload,omitempty"`
	Signatures   []*Signature      `protobuf:"bytes,7,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Status       AttestationStatus `protobuf:"varint,8,opt,name=status,proto3,enum=lucidchain.attestor.v1.AttestationStatus" json:"status,omitempty"`
	IssuedHeight uint64            `protobuf:"varint,9,opt,name=issued_height,json=issuedHeight,proto3" json:"issued_height,omitempty"`
	IssuedAt     time.Time         `protobuf:"bytes,10,opt,name=issued_at,json=issuedAt,proto3,stdtime" json:"issued_at"`
	ExpiresAt    time.Time         `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3,stdtime" json:"expires_at"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{2}
}
func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return m.Size()
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attestation) GetSchemaId() string {
	if m != nil {
		return m.SchemaId
	}
	return ""
}

func (m *Attestation) GetAttestorId() string {
	if m != nil {
		return m.AttestorId
	}
	return ""
}

func (m *Attestation) GetSidechainId() string {
	if m != nil {
		return m.SidechainId
	}
	return ""
}

func (m *Attestation) GetCheckpointSequence() uint64 {
	if m != nil {
		return m.CheckpointSequence
	}
	return 0
}

func (m *Attestation) GetClaimPayload() []byte {
	if m != nil {
		return m.ClaimPayload
	}
	return nil
}

func (m *Attestation) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Attestation) GetStatus() AttestationStatus {
	if m != nil {
		return m.Status
	}
	return AttestationStatus_ATTESTATION_STATUS_UNSPECIFIED
}

func (m *Attestation) GetIssuedHeight() uint64 {
	if m != nil {
		return m.IssuedHeight
	}
	return 0
}

func (m *Attestation) GetIssuedAt() time.Time {
	if m != nil {
		return m.IssuedAt
	}
	return time.Time{}
}

func (m *Attestation) GetExpiresAt() time.Time {
	if m != nil {
		return m.ExpiresAt
	}
	return time.Time{}
}

type Signature struct {
	Pubkey    string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{3}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return m.Size()
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Dispute is raised against an Attestation within its schema's dispute window.
type Dispute struct {
	Id            string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttestationId string                `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	Challenger    string                `protobuf:"bytes,3,opt,name=challenger,proto3" json:"challenger,omitempty"`
	EvidenceUri   string                `protobuf:"bytes,4,opt,name=evidence_uri,json=evidenceUri,proto3" json:"evidence_uri,omitempty"`
	BondAmount    cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=bond_amount,json=bondAmount,proto3,customtype=cosmossdk.io/math.Int" json:"bond_amount"`
	Resolved      bool                  `protobuf:"varint,6,opt,name=resolved,proto3" json:"resolved,omitempty"`
	Upheld        bool                  `protobuf:"varint,7,opt,name=upheld,proto3" json:"upheld,omitempty"`
	RaisedAt      time.Time             `protobuf:"bytes,8,opt,name=raised_at,json=raisedAt,proto3,stdtime" json:"raised_at"`
	ResolvedAt    *time.Time            `protobuf:"bytes,9,opt,name=resolved_at,json=resolvedAt,proto3,stdtime" json:"resolved_at,omitempty"`
}

func (m *Dispute) Reset()         { *m = Dispute{} }
func (m *Dispute) String() string { return proto.CompactTextString(m) }
func (*Dispute) ProtoMessage()    {}
func (*Dispute) Descriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{4}
}
func (m *Dispute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Dispute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Dispute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Dispute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dispute.Merge(m, src)
}
func (m *Dispute) XXX_Size() int {
	return m.Size()
}
func (m *Dispute) XXX_DiscardUnknown() {
	xxx_messageInfo_Dispute.DiscardUnknown(m)
}

var xxx_messageInfo_Dispute proto.InternalMessageInfo

func (m *Dispute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dispute) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

func (m *Dispute) GetChallenger() string {
	if m != nil {
		return m.Challenger
	}
	return ""
}

func (m *Dispute) GetEvidenceUri() string {
	if m != nil {
		return m.EvidenceUri
	}
	return ""
}

func (m *Dispute) GetResolved() bool {
	if m != nil {
		return m.Resolved
	}
	return false
}

func (m *Dispute) GetUpheld() bool {
	if m != nil {
		return m.Upheld
	}
	return false
}

func (m *Dispute) GetRaisedAt() time.Time {
	if m != nil {
		return m.RaisedAt
	}
	return time.Time{}
}

func (m *Dispute) GetResolvedAt() *time.Time {
	if m != nil {
		return m.ResolvedAt
	}
	return nil
}

// Params defines module-wide parameters, settable via governance.
type Params struct {
	MinAttestorBond cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=min_attestor_bond,json=minAttestorBond,proto3,customtype=cosmossdk.io/math.Int" json:"min_attestor_bond"`
	MinDisputeBond  cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=min_dispute_bond,json=minDisputeBond,proto3,customtype=cosmossdk.io/math.Int" json:"min_dispute_bond"`
	// Governance/arbiter mechanism resolves disputes; this is the account (e.g.
	// gov module) authorized to call ResolveDispute. A future version may replace
	// this with a dedicated arbitration module.
	DisputeResolverAuthority string `protobuf:"bytes,3,opt,name=dispute_resolver_authority,json=disputeResolverAuthority,proto3" json:"dispute_resolver_authority,omitempty"`
	MaxClaimPayloadBytes     uint32 `protobuf:"varint,4,opt,name=max_claim_payload_bytes,json=maxClaimPayloadBytes,proto3" json:"max_claim_payload_bytes,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_451fa12c266340bc, []int{5}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDisputeResolverAuthority() string {
	if m != nil {
		return m.DisputeResolverAuthority
	}
	return ""
}

func (m *Params) GetMaxClaimPayloadBytes() uint32 {
	if m != nil {
		return m.MaxClaimPayloadBytes
	}
	return 0
}

func init() {
	proto.RegisterEnum("lucidchain.attestor.v1.AttestorStatus", AttestorStatus_name, AttestorStatus_value)
	proto.RegisterEnum("lucidchain.attestor.v1.AttestationStatus", AttestationStatus_name, AttestationStatus_value)
	proto.RegisterType((*Attestor)(nil), "lucidchain.attestor.v1.Attestor")
	proto.RegisterType((*AttestationSchema)(nil), "lucidchain.attestor.v1.AttestationSchema")
	proto.RegisterType((*Attestation)(nil), "lucidchain.attestor.v1.Attestation")
	proto.RegisterType((*Signature)(nil), "lucidchain.attestor.v1.Signature")
	proto.RegisterType((*Dispute)(nil), "lucidchain.attestor.v1.Dispute")
	proto.RegisterType((*Params)(nil), "lucidchain.attestor.v1.Params")
}

func init() {
	proto.RegisterFile("lucidchain/attestor/v1/attestor.proto", fileDescriptor_451fa12c266340bc)
}

var fileDescriptor_451fa12c266340bc = []byte{
	// 1261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x35, 0x25, 0x59, 0x91, 0x56, 0x96, 0xa3, 0x6c, 0x1c, 0x87, 0x55, 0x1a, 0xc9, 0x71, 0x90,
	0x42, 0x49, 0x01, 0x09, 0x71, 0x3f, 0x0e, 0x45, 0x11, 0x80, 0xb6, 0xd4, 0x84, 0x68, 0x60, 0x0b,
	0xa4, 0x94, 0x16, 0xbd, 0x10, 0x6b, 0xee, 0x56, 0x5a, 0x44, 0xe4, 0x32, 0xdc, 0xa5, 0x63, 0xf5,
	0x0f, 0xf4, 0x54, 0x20, 0xb7, 0x5e, 0xfb, 0x5b, 0x7a, 0xca, 0x31, 0xc7, 0xb6, 0x87, 0xb4, 0x48,
	0x2e, 0xfd, 0x0b, 0xbd, 0x15, 0xbb, 0x4b, 0x52, 0xf2, 0x47, 0xda, 0xf8, 0xc6, 0x7d, 0x6f, 0x66,
	0xc4, 0x7d, 0xf3, 0x66, 0x28, 0x70, 0x67, 0x96, 0xf8, 0x14, 0xfb, 0x53, 0x44, 0xc3, 0x1e, 0x12,
	0x82, 0x70, 0xc1, 0xe2, 0xde, 0xd1, 0xfd, 0xfc, 0xb9, 0x1b, 0xc5, 0x4c, 0x30, 0xb8, 0xb9, 0x08,
	0xeb, 0xe6, 0xd4, 0xd1, 0xfd, 0xe6, 0xc6, 0x84, 0x4d, 0x98, 0x0a, 0xe9, 0xc9, 0x27, 0x1d, 0xdd,
	0x6c, 0x4f, 0x18, 0x9b, 0xcc, 0x48, 0x4f, 0x9d, 0x0e, 0x93, 0xef, 0x7b, 0x82, 0x06, 0x84, 0x0b,
	0x14, 0x44, 0x3a, 0x60, 0xfb, 0x9f, 0x22, 0xa8, 0x58, 0x69, 0x19, 0xb8, 0x0e, 0x0a, 0x14, 0x9b,
	0xc6, 0x96, 0xd1, 0xa9, 0x3a, 0x05, 0x8a, 0x21, 0x04, 0xa5, 0x10, 0x05, 0xc4, 0x2c, 0x28, 0x44,
	0x3d, 0xc3, 0x26, 0xa8, 0xb0, 0x88, 0xc4, 0x48, 0xb0, 0xd8, 0x2c, 0x2a, 0x3c, 0x3f, 0xc3, 0x1d,
	0x70, 0x0d, 0x25, 0x62, 0xca, 0x62, 0xfa, 0x03, 0xc1, 0x1e, 0xf7, 0xa7, 0x24, 0x40, 0x1e, 0xc5,
	0xdc, 0x2c, 0x6d, 0x15, 0x3b, 0x55, 0xe7, 0xea, 0x82, 0x74, 0x15, 0x67, 0x63, 0x0e, 0xef, 0x80,
	0x75, 0x4e, 0x27, 0x21, 0x89, 0xbd, 0x28, 0x39, 0x7c, 0x4a, 0xe6, 0xdc, 0x5c, 0x55, 0xc1, 0x75,
	0x8d, 0x0e, 0x35, 0x08, 0x7b, 0xe0, 0xaa, 0x04, 0x90, 0x48, 0x62, 0xe2, 0x89, 0x69, 0x4c, 0xf8,
	0x94, 0xcd, 0xb0, 0x59, 0xde, 0x32, 0x3a, 0x75, 0x07, 0xe6, 0xd4, 0x28, 0x63, 0xe0, 0x03, 0x50,
	0xe6, 0x02, 0x89, 0x84, 0x9b, 0x97, 0xb6, 0x8c, 0xce, 0xfa, 0xce, 0x47, 0xdd, 0xf3, 0x85, 0xeb,
	0x66, 0xb7, 0x77, 0x55, 0xb4, 0x93, 0x66, 0xc1, 0x07, 0xa0, 0x76, 0xc8, 0x42, 0xec, 0xa1, 0x80,
	0x25, 0xa1, 0x30, 0x2b, 0xf2, 0xaa, 0xbb, 0x37, 0x5f, 0xbe, 0x6e, 0xaf, 0xfc, 0xf1, 0xba, 0x7d,
	0xcd, 0x67, 0x3c, 0x60, 0x9c, 0xe3, 0xa7, 0x5d, 0xca, 0x7a, 0x01, 0x12, 0xd3, 0xae, 0x1d, 0x0a,
	0x07, 0xc8, 0x0c, 0x4b, 0x25, 0xc0, 0xbb, 0xa0, 0x11, 0x93, 0x28, 0x11, 0x48, 0x50, 0x16, 0x7a,
	0xdc, 0x67, 0x31, 0x31, 0xab, 0x5b, 0x46, 0xa7, 0xe8, 0x5c, 0x5e, 0xe0, 0xae, 0x84, 0xa1, 0x0d,
	0xea, 0x31, 0x99, 0x50, 0x2e, 0x48, 0x4c, 0xb0, 0x87, 0x84, 0x09, 0xb6, 0x8c, 0x4e, 0x6d, 0xa7,
	0xd9, 0xd5, 0xcd, 0xeb, 0x66, 0xcd, 0xeb, 0x8e, 0xb2, 0xe6, 0xed, 0x56, 0xe4, 0x8b, 0xbc, 0xf8,
	0xb3, 0x6d, 0x38, 0x6b, 0x8b, 0x54, 0x4b, 0x48, 0x35, 0xfd, 0x98, 0x60, 0x12, 0x0a, 0x8a, 0x66,
	0x5e, 0x12, 0x53, 0xb3, 0xa6, 0x7a, 0x54, 0x5f, 0xa0, 0xe3, 0x98, 0x7e, 0x51, 0xfa, 0xfb, 0x97,
	0xb6, 0xb1, 0xfd, 0xba, 0x00, 0xae, 0xe8, 0xdb, 0xa7, 0x2f, 0x23, 0x7b, 0x72, 0xc6, 0x04, 0x1b,
	0x60, 0x55, 0x50, 0x31, 0xcb, 0x5c, 0xa0, 0x0f, 0x70, 0x13, 0x94, 0x31, 0x0b, 0x10, 0x0d, 0x53,
	0x13, 0xa4, 0x27, 0xf8, 0x31, 0xb8, 0xe2, 0xcf, 0x10, 0x0d, 0x3c, 0x4c, 0xb8, 0x1f, 0xd3, 0x48,
	0x16, 0x36, 0x4b, 0x2a, 0xa4, 0xa1, 0x88, 0xfe, 0x02, 0x87, 0x2d, 0x00, 0xc8, 0xb1, 0x3f, 0x4b,
	0x38, 0x65, 0xa1, 0xec, 0xbb, 0x8c, 0x5a, 0x42, 0xa4, 0x9f, 0x62, 0xf2, 0x2c, 0xa1, 0x52, 0x16,
	0x8c, 0x04, 0xf2, 0x38, 0x4b, 0x62, 0x9f, 0x70, 0xb3, 0xac, 0xfd, 0x94, 0x91, 0x7d, 0x24, 0x90,
	0xab, 0x29, 0xf8, 0x39, 0xb8, 0x7e, 0x84, 0x66, 0x14, 0x53, 0x31, 0xf7, 0x22, 0x12, 0x53, 0x86,
	0x3d, 0x4e, 0x7c, 0x16, 0x62, 0x6d, 0x84, 0x92, 0x73, 0x2d, 0xa3, 0x87, 0x8a, 0x75, 0x35, 0x09,
	0x3f, 0x05, 0x9b, 0x98, 0xf2, 0x28, 0x11, 0xc4, 0x7b, 0x4e, 0x43, 0xcc, 0x9e, 0xe7, 0x69, 0x15,
	0x95, 0xb6, 0x91, 0xb2, 0xdf, 0x28, 0x32, 0xcb, 0xda, 0x04, 0x65, 0xe4, 0x0b, 0x7a, 0xa4, 0x7b,
	0x5b, 0x71, 0xd2, 0x53, 0x2a, 0xf0, 0x4f, 0x25, 0x50, 0x5b, 0x12, 0xf8, 0x8c, 0xb4, 0x37, 0x40,
	0x35, 0x1f, 0x92, 0x54, 0xde, 0x0a, 0x4f, 0x27, 0x03, 0xb6, 0x41, 0x2d, 0xb3, 0xa9, 0xa4, 0xb5,
	0xcc, 0x20, 0x83, 0x6c, 0x0c, 0x6f, 0x81, 0x35, 0x4e, 0x31, 0x51, 0x8e, 0x96, 0x11, 0x5a, 0xe5,
	0x5a, 0x8e, 0xd9, 0x58, 0x4e, 0x8d, 0x3f, 0x25, 0xfe, 0xd3, 0x88, 0xd1, 0x50, 0x78, 0x9c, 0x3c,
	0x4b, 0x48, 0xe8, 0x13, 0xa5, 0x74, 0xc9, 0x81, 0x0b, 0xca, 0x4d, 0x19, 0x78, 0x1b, 0xd4, 0x75,
	0xfb, 0x22, 0x34, 0x9f, 0x31, 0xa4, 0x07, 0x6c, 0xcd, 0x59, 0x53, 0xe0, 0x50, 0x63, 0xd0, 0x02,
	0x20, 0x1f, 0x38, 0xa9, 0x6a, 0xb1, 0x53, 0xdb, 0xb9, 0xf5, 0xae, 0xf1, 0x72, 0xb3, 0x48, 0x67,
	0x29, 0x09, 0x5a, 0xf9, 0x74, 0x56, 0xd4, 0x74, 0xde, 0xfd, 0xef, 0xe9, 0xd4, 0xfe, 0x3c, 0x39,
	0xa0, 0xb7, 0x41, 0x9d, 0x72, 0x9e, 0x10, 0xec, 0x4d, 0x09, 0x9d, 0x4c, 0x85, 0xea, 0x40, 0xc9,
	0x59, 0xd3, 0xe0, 0x23, 0x85, 0x41, 0x0b, 0x54, 0xd3, 0xa0, 0x0b, 0x8e, 0x55, 0x45, 0xa7, 0x59,
	0x02, 0xee, 0x49, 0x93, 0x46, 0x34, 0x26, 0x5c, 0xd6, 0xa8, 0x5d, 0xa0, 0x46, 0x35, 0xcd, 0xb3,
	0x44, 0xea, 0x07, 0x0b, 0x54, 0x73, 0x39, 0xa4, 0x75, 0xf4, 0xc6, 0x4b, 0x0d, 0x91, 0x9e, 0xe0,
	0x87, 0xa0, 0x9a, 0x0b, 0xa5, 0x4c, 0xb1, 0xe6, 0x2c, 0x80, 0xed, 0x1f, 0x8b, 0xe0, 0x52, 0x5f,
	0x3b, 0xf1, 0x8c, 0x9d, 0xee, 0x80, 0x75, 0xb4, 0x90, 0x6b, 0xe1, 0xa9, 0xfa, 0x12, 0x6a, 0x63,
	0x39, 0x75, 0xfe, 0x14, 0xcd, 0x66, 0x24, 0x9c, 0x90, 0x6c, 0x87, 0x2f, 0x21, 0xd2, 0x57, 0xe4,
	0x88, 0x62, 0xe9, 0x07, 0xb5, 0x41, 0x52, 0x5f, 0x65, 0xd8, 0x38, 0xa6, 0xa7, 0x97, 0xe3, 0xea,
	0x45, 0x97, 0x63, 0x13, 0x54, 0x62, 0xc2, 0xd9, 0xec, 0x88, 0x68, 0x87, 0x55, 0x9c, 0xfc, 0x2c,
	0x75, 0x49, 0xa2, 0x29, 0x99, 0x61, 0x35, 0xaf, 0x15, 0x27, 0x3d, 0xc9, 0x56, 0xc6, 0x88, 0x72,
	0xdd, 0xca, 0xca, 0x45, 0x5a, 0xa9, 0xd3, 0x2c, 0x01, 0x07, 0xa0, 0x96, 0xfd, 0x8c, 0x87, 0xb4,
	0x61, 0xfe, 0xbf, 0x88, 0xa1, 0x8a, 0x80, 0x2c, 0x31, 0x6f, 0xe6, 0xcf, 0x05, 0x50, 0x1e, 0xa2,
	0x18, 0x05, 0x1c, 0xda, 0xe0, 0x4a, 0x40, 0x43, 0x2f, 0x1f, 0x57, 0x79, 0x53, 0xd3, 0x78, 0x1f,
	0x51, 0x2e, 0x07, 0x34, 0xcc, 0x3e, 0x40, 0xbb, 0x2c, 0xc4, 0xf0, 0x21, 0x68, 0xc8, 0x52, 0xd9,
	0x2a, 0x52, 0x95, 0x0a, 0xef, 0x53, 0x69, 0x3d, 0xa0, 0x61, 0x6a, 0x0c, 0x55, 0xe8, 0x4b, 0xd0,
	0xcc, 0x8a, 0xa4, 0xaf, 0x1e, 0x7b, 0xe9, 0xf7, 0x57, 0xcc, 0xd3, 0xae, 0x9b, 0x69, 0x84, 0x93,
	0x06, 0x58, 0x19, 0x0f, 0x3f, 0x03, 0xd7, 0x03, 0x74, 0xec, 0x9d, 0xd8, 0x05, 0xde, 0xe1, 0x5c,
	0x10, 0xae, 0xec, 0x50, 0x77, 0x36, 0x02, 0x74, 0xbc, 0xb7, 0xb4, 0x14, 0x76, 0x25, 0xa7, 0x95,
	0xb9, 0xf7, 0xab, 0x01, 0xd6, 0x4f, 0x7e, 0x55, 0x61, 0x1b, 0xdc, 0xb0, 0x46, 0xa3, 0x81, 0x3b,
	0x3a, 0x70, 0x3c, 0x77, 0x64, 0x8d, 0xc6, 0xae, 0x37, 0xde, 0x77, 0x87, 0x83, 0x3d, 0xfb, 0x2b,
	0x7b, 0xd0, 0x6f, 0xac, 0xc0, 0x1b, 0xe0, 0xfa, 0xe9, 0x80, 0xe1, 0x60, 0xbf, 0x6f, 0xef, 0x3f,
	0x6c, 0x18, 0xb0, 0x09, 0x36, 0x4f, 0x93, 0xd6, 0xde, 0xc8, 0x7e, 0x32, 0x68, 0x14, 0xe0, 0x4d,
	0xf0, 0xc1, 0x69, 0xce, 0x1d, 0xbb, 0x32, 0x77, 0xd0, 0x6f, 0x14, 0xcf, 0xab, 0xeb, 0x3e, 0xb6,
	0xdc, 0x47, 0x83, 0x7e, 0xa3, 0x74, 0x5e, 0xdd, 0xc1, 0xb7, 0xf6, 0x68, 0xd0, 0x6f, 0xac, 0xde,
	0xfb, 0xdd, 0x38, 0xf9, 0x71, 0xd4, 0xf7, 0xd8, 0x06, 0x2d, 0x9d, 0x61, 0x8d, 0xec, 0x83, 0xfd,
	0xf3, 0xaf, 0x92, 0xbf, 0xd1, 0x89, 0x98, 0xf4, 0x85, 0x8d, 0x85, 0x14, 0x27, 0xe8, 0xbe, 0xed,
	0x0e, 0xc7, 0xf2, 0x97, 0x0b, 0xef, 0xc8, 0x1f, 0x0f, 0x1f, 0x0d, 0x1e, 0xcb, 0x1b, 0xdd, 0x02,
	0x37, 0xcf, 0xa1, 0x0f, 0x9e, 0x0c, 0x9c, 0xd1, 0xd8, 0xd9, 0x57, 0xf7, 0x6a, 0x81, 0xe6, 0x39,
	0x21, 0xce, 0xe0, 0xc9, 0xc1, 0xd7, 0xf2, 0x6e, 0xbb, 0xf6, 0xcb, 0x37, 0x2d, 0xe3, 0xd5, 0x9b,
	0x96, 0xf1, 0xd7, 0x9b, 0x96, 0xf1, 0xe2, 0x6d, 0x6b, 0xe5, 0xd5, 0xdb, 0xd6, 0xca, 0x6f, 0x6f,
	0x5b, 0x2b, 0xdf, 0xf5, 0x26, 0x54, 0x4c, 0x93, 0xc3, 0xae, 0xcf, 0x82, 0x9e, 0xda, 0xc8, 0x11,
	0x9a, 0xf7, 0x96, 0xfe, 0x98, 0x1e, 0x2f, 0xfe, 0x9a, 0x8a, 0x79, 0x44, 0xf8, 0x61, 0x59, 0x4d,
	0xcd, 0x27, 0xff, 0x0e, 0x00, 0x2b, 0xc2, 0x85, 0x0a, 0xbe, 0x0a, 0x00, 0x00,
}

func (this *Attestor) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Attestor)
	if !ok {
		that2, ok := that.(Attestor)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Operator != that1.Operator {
		return false
	}
	if len(this.AuthorizedSchemaIds) != len(that1.AuthorizedSchemaIds) {
		return false
	}
	for i := range this.AuthorizedSchemaIds {
		if this.AuthorizedSchemaIds[i] != that1.AuthorizedSchemaIds[i] {
			return false
		}
	}
	if len(this.SignerPubkeys) != len(that1.SignerPubkeys) {
		return false
	}
	for i := range this.SignerPubkeys {
		if this.SignerPubkeys[i] != that1.SignerPubkeys[i] {
			return false
		}
	}
	if this.SignatureThreshold != that1.SignatureThreshold {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.BondAmount.Equal(that1.BondAmount) {
		return false
	}
	if this.ReputationScore != that1.ReputationScore {
		return false
	}
	if !this.RegisteredAt.Equal(that1.RegisteredAt) {
		return false
	}
	if this.CredentialUri != that1.CredentialUri {
		return false
	}
	return true
}
func (this *AttestationSchema) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AttestationSchema)
	if !ok {
		that2, ok := that.(AttestationSchema)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if this.ClaimDescription != that1.ClaimDescription {
		return false
	}
	if this.Exclusions != that1.Exclusions {
		return false
	}
	if len(this.RequiredDataSources) != len(that1.RequiredDataSources) {
		return false
	}
	for i := range this.RequiredDataSources {
		if this.RequiredDataSources[i] != that1.RequiredDataSources[i] {
			return false
		}
	}
	if this.ValidityPeriodSeconds != that1.ValidityPeriodSeconds {
		return false
	}
	if this.DisputeWindowSeconds != that1.DisputeWindowSeconds {
		return false
	}
	if this.Active != that1.Active {
		return false
	}
	return true
}
func (this *Attestation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Attestation)
	if !ok {
		that2, ok := that.(Attestation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.SchemaId != that1.SchemaId {
		return false
	}
	if this.AttestorId != that1.AttestorId {
		return false
	}
	if this.SidechainId != that1.SidechainId {
		return false
	}
	if this.CheckpointSequence != that1.CheckpointSequence {
		return false
	}
	if !bytes.Equal(this.ClaimPayload, that1.ClaimPayload) {
		return false
	}
	if len(this.Signatures) != len(that1.Signatures) {
		return false
	}
	for i := range this.Signatures {
		if !this.Signatures[i].Equal(that1.Signatures[i]) {
			return false
		}
	}
	if this.Status != that1.Status {
		return false
	}
	if this.IssuedHeight != that1.IssuedHeight {
		return false
	}
	if !this.IssuedAt.Equal(that1.IssuedAt) {
		return false
	}
	if !this.ExpiresAt.Equal(that1.ExpiresAt) {
		return false
	}
	return true
}
func (this *Dispute) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Dispute)
	if !ok {
		that2, ok := that.(Dispute)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.AttestationId != that1.AttestationId {
		return false
	}
	if this.Challenger != that1.Challenger {
		return false
	}
	if this.EvidenceUri != that1.EvidenceUri {
		return false
	}
	if !this.BondAmount.Equal(that1.BondAmount) {
		return false
	}
	if this.Resolved != that1.Resolved {
		return false
	}
	if this.Upheld != that1.Upheld {
		return false
	}
	if !this.RaisedAt.Equal(that1.RaisedAt) {
		return false
	}
	if that1.ResolvedAt == nil {
		if this.ResolvedAt != nil {
			return false
		}
	} else if !this.ResolvedAt.Equal(*that1.ResolvedAt) {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinAttestorBond.Equal(that1.MinAttestorBond) {
		return false
	}
	if !this.MinDisputeBond.Equal(that1.MinDisputeBond) {
		return false
	}
	if this.DisputeResolverAuthority != that1.DisputeResolverAuthority {
		return false
	}
	if this.MaxClaimPayloadBytes != that1.MaxClaimPayloadBytes {
		return false
	}
	return true
}
func (m *Attestor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attestor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attestor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CredentialUri) > 0 {
		i -= len(m.CredentialUri)
		copy(dAtA[i:], m.CredentialUri)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.CredentialUri)))
		i--
		dAtA[i] = 0x5a
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.RegisteredAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RegisteredAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintAttestor(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	if m.ReputationScore != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.ReputationScore))
		i--
		dAtA[i] = 0x48
	}
	{
		size := m.BondAmount.Size()
		i -= size
		if _, err := m.BondAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAttestor(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.Status != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.SignatureThreshold != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.SignatureThreshold))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SignerPubkeys) > 0 {
		for iNdEx := len(m.SignerPubkeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SignerPubkeys[iNdEx])
			copy(dAtA[i:], m.SignerPubkeys[iNdEx])
			i = encodeVarintAttestor(dAtA, i, uint64(len(m.SignerPubkeys[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.AuthorizedSchemaIds) > 0 {
		for iNdEx := len(m.AuthorizedSchemaIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AuthorizedSchemaIds[iNdEx])
			copy(dAtA[i:], m.AuthorizedSchemaIds[iNdEx])
			i = encodeVarintAttestor(dAtA, i, uint64(len(m.AuthorizedSchemaIds[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AttestationSchema) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttestationSchema) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttestationSchema) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.DisputeWindowSeconds != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.DisputeWindowSeconds))
		i--
		dAtA[i] = 0x40
	}
	if m.ValidityPeriodSeconds != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.ValidityPeriodSeconds))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RequiredDataSources) > 0 {
		for iNdEx := len(m.RequiredDataSources) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RequiredDataSources[iNdEx])
			copy(dAtA[i:], m.RequiredDataSources[iNdEx])
			i = encodeVarintAttestor(dAtA, i, uint64(len(m.RequiredDataSources[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Exclusions) > 0 {
		i -= len(m.Exclusions)
		copy(dAtA[i:], m.Exclusions)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Exclusions)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ClaimDescription) > 0 {
		i -= len(m.ClaimDescription)
		copy(dAtA[i:], m.ClaimDescription)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.ClaimDescription)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Attestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpiresAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpiresAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintAttestor(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x5a
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.IssuedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.IssuedAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintAttestor(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x52
	if m.IssuedHeight != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.IssuedHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.Status != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAttestor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ClaimPayload) > 0 {
		i -= len(m.ClaimPayload)
		copy(dAtA[i:], m.ClaimPayload)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.ClaimPayload)))
		i--
		dAtA[i] = 0x32
	}
	if m.CheckpointSequence != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.CheckpointSequence))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SidechainId) > 0 {
		i -= len(m.SidechainId)
		copy(dAtA[i:], m.SidechainId)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.SidechainId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AttestorId) > 0 {
		i -= len(m.AttestorId)
		copy(dAtA[i:], m.AttestorId)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.AttestorId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SchemaId) > 0 {
		i -= len(m.SchemaId)
		copy(dAtA[i:], m.SchemaId)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.SchemaId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Signature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Signature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Signature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Dispute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dispute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Dispute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResolvedAt != nil {
		n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ResolvedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ResolvedAt):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintAttestor(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x4a
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.RaisedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RaisedAt):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintAttestor(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x42
	if m.Upheld {
		i--
		if m.Upheld {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Resolved {
		i--
		if m.Resolved {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.BondAmount.Size()
		i -= size
		if _, err := m.BondAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAttestor(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.EvidenceUri) > 0 {
		i -= len(m.EvidenceUri)
		copy(dAtA[i:], m.EvidenceUri)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.EvidenceUri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Challenger) > 0 {
		i -= len(m.Challenger)
		copy(dAtA[i:], m.Challenger)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Challenger)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxClaimPayloadBytes != 0 {
		i = encodeVarintAttestor(dAtA, i, uint64(m.MaxClaimPayloadBytes))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DisputeResolverAuthority) > 0 {
		i -= len(m.DisputeResolverAuthority)
		copy(dAtA[i:], m.DisputeResolverAuthority)
		i = encodeVarintAttestor(dAtA, i, uint64(len(m.DisputeResolverAuthority)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.MinDisputeBond.Size()
		i -= size
		if _, err := m.MinDisputeBond.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAttestor(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.MinAttestorBond.Size()
		i -= size
		if _, err := m.MinAttestorBond.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAttestor(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintAttestor(dAtA []byte, offset int, v uint64) int {
	offset -= sovAttestor(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Attestor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	if len(m.AuthorizedSchemaIds) > 0 {
		for _, s := range m.AuthorizedSchemaIds {
			l = len(s)
			n += 1 + l + sovAttestor(uint64(l))
		}
	}
	if len(m.SignerPubkeys) > 0 {
		for _, s := range m.SignerPubkeys {
			l = len(s)
			n += 1 + l + sovAttestor(uint64(l))
		}
	}
	if m.SignatureThreshold != 0 {
		n += 1 + sovAttestor(uint64(m.SignatureThreshold))
	}
	if m.Status != 0 {
		n += 1 + sovAttestor(uint64(m.Status))
	}
	l = m.BondAmount.Size()
	n += 1 + l + sovAttestor(uint64(l))
	if m.ReputationScore != 0 {
		n += 1 + sovAttestor(uint64(m.ReputationScore))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RegisteredAt)
	n += 1 + l + sovAttestor(uint64(l))
	l = len(m.CredentialUri)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	return n
}

func (m *AttestationSchema) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.ClaimDescription)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Exclusions)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	if len(m.RequiredDataSources) > 0 {
		for _, s := range m.RequiredDataSources {
			l = len(s)
			n += 1 + l + sovAttestor(uint64(l))
		}
	}
	if m.ValidityPeriodSeconds != 0 {
		n += 1 + sovAttestor(uint64(m.ValidityPeriodSeconds))
	}
	if m.DisputeWindowSeconds != 0 {
		n += 1 + sovAttestor(uint64(m.DisputeWindowSeconds))
	}
	if m.Active {
		n += 2
	}
	return n
}

func (m *Attestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.SchemaId)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.AttestorId)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.SidechainId)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	if m.CheckpointSequence != 0 {
		n += 1 + sovAttestor(uint64(m.CheckpointSequence))
	}
	l = len(m.ClaimPayload)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovAttestor(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovAttestor(uint64(m.Status))
	}
	if m.IssuedHeight != 0 {
		n += 1 + sovAttestor(uint64(m.IssuedHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.IssuedAt)
	n += 1 + l + sovAttestor(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpiresAt)
	n += 1 + l + sovAttestor(uint64(l))
	return n
}

func (m *Signature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	return n
}

func (m *Dispute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.Challenger)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = len(m.EvidenceUri)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	l = m.BondAmount.Size()
	n += 1 + l + sovAttestor(uint64(l))
	if m.Resolved {
		n += 2
	}
	if m.Upheld {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RaisedAt)
	n += 1 + l + sovAttestor(uint64(l))
	if m.ResolvedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ResolvedAt)
		n += 1 + l + sovAttestor(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinAttestorBond.Size()
	n += 1 + l + sovAttestor(uint64(l))
	l = m.MinDisputeBond.Size()
	n += 1 + l + sovAttestor(uint64(l))
	l = len(m.DisputeResolverAuthority)
	if l > 0 {
		n += 1 + l + sovAttestor(uint64(l))
	}
	if m.MaxClaimPayloadBytes != 0 {
		n += 1 + sovAttestor(uint64(m.MaxClaimPayloadBytes))
	}
	return n
}

func sovAttestor(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAttestor(x uint64) (n int) {
	return sovAttestor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Attestor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attestor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attestor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizedSchemaIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizedSchemaIds = append(m.AuthorizedSchemaIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerPubkeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerPubkeys = append(m.SignerPubkeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureThreshold", wireType)
			}
			m.SignatureThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignatureThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= AttestorStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReputationScore", wireType)
			}
			m.ReputationScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReputationScore |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.RegisteredAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AttestationSchema) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttestationSchema: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttestationSchema: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exclusions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exclusions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredDataSources", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredDataSources = append(m.RequiredDataSources, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidityPeriodSeconds", wireType)
			}
			m.ValidityPeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidityPeriodSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeWindowSeconds", wireType)
			}
			m.DisputeWindowSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeWindowSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAttestor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Attestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SchemaId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SidechainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SidechainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointSequence", wireType)
			}
			m.CheckpointSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckpointSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimPayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimPayload = append(m.ClaimPayload[:0], dAtA[iNdEx:postIndex]...)
			if m.ClaimPayload == nil {
				m.ClaimPayload = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, &Signature{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= AttestationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuedHeight", wireType)
			}
			m.IssuedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.IssuedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpiresAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Signature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Signature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Signature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Dispute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Dispute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Dispute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenger = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resolved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Resolved = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upheld", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Upheld = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaisedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.RaisedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ResolvedAt == nil {
				m.ResolvedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ResolvedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAttestorBond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinAttestorBond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDisputeBond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinDisputeBond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeResolverAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisputeResolverAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClaimPayloadBytes", wireType)
			}
			m.MaxClaimPayloadBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClaimPayloadBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAttestor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAttestor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAttestor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAttestor
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAttestor
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAttestor
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAttestor        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAttestor          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAttestor = fmt.Errorf("proto: unexpected end of group")
)
